// Code generated by Fern. DO NOT EDIT.

package schema

import (
	context "context"

	core "github.com/Trace-DB/tracedb-go/core"
	internal "github.com/Trace-DB/tracedb-go/internal"
	option "github.com/Trace-DB/tracedb-go/option"
	tracedb "github.com/Trace-DB/tracedb-go/tracedb"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Current TraceDB v1 product route. This OpenAPI artifact is generated from the checked-in route manifest.
func (c *Client) PostSchemaApply(
	ctx context.Context,
	request *tracedb.TableSchema,
	opts ...option.RequestOption,
) (*tracedb.EpochResponse, error) {
	response, err := c.WithRawResponse.PostSchemaApply(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
