// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/Trace-DB/tracedb-go/core"
	internal "github.com/Trace-DB/tracedb-go/internal"
	admin "github.com/Trace-DB/tracedb-go/tracedb/admin"
	catalog "github.com/Trace-DB/tracedb-go/tracedb/catalog"
	health "github.com/Trace-DB/tracedb-go/tracedb/health"
	metrics "github.com/Trace-DB/tracedb-go/tracedb/metrics"
	query "github.com/Trace-DB/tracedb-go/tracedb/query"
	readiness "github.com/Trace-DB/tracedb-go/tracedb/readiness"
	records "github.com/Trace-DB/tracedb-go/tracedb/records"
	schema "github.com/Trace-DB/tracedb-go/tracedb/schema"
)

type Client struct {
	Admin     *admin.Client
	Catalog   *catalog.Client
	Query     *query.Client
	Health    *health.Client
	Records   *records.Client
	Metrics   *metrics.Client
	Readiness *readiness.Client
	Schema    *schema.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		Admin:     admin.NewClient(options),
		Catalog:   catalog.NewClient(options),
		Query:     query.NewClient(options),
		Health:    health.NewClient(options),
		Records:   records.NewClient(options),
		Metrics:   metrics.NewClient(options),
		Readiness: readiness.NewClient(options),
		Schema:    schema.NewClient(options),
		options:   options,
		baseURL:   options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
