// Code generated by Fern. DO NOT EDIT.

package tracedb

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"

	internal "github.com/Trace-DB/tracedb-go/internal"
)

var (
	getAdminJobsRequestFieldDatabaseID = big.NewInt(1 << 0)
	getAdminJobsRequestFieldBranchID   = big.NewInt(1 << 1)
)

type GetAdminJobsRequest struct {
	// Canonical managed-routing database identifier for bodyless routes. SDKs must use this parameter name (not db_id, databaseId, or similar variants) so all SDKs target the same gateway routing key.
	DatabaseID *string `json:"-" url:"database_id,omitempty"`
	// Canonical managed-routing branch identifier for bodyless routes. SDKs must use this parameter name (not br_id, branchId, or similar variants) so all SDKs target the same gateway routing key.
	BranchID *string `json:"-" url:"branch_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetAdminJobsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetDatabaseID sets the DatabaseID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAdminJobsRequest) SetDatabaseID(databaseID *string) {
	g.DatabaseID = databaseID
	g.require(getAdminJobsRequestFieldDatabaseID)
}

// SetBranchID sets the BranchID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAdminJobsRequest) SetBranchID(branchID *string) {
	g.BranchID = branchID
	g.require(getAdminJobsRequestFieldBranchID)
}

var (
	postAdminCompactRequestFieldIdempotencyKey = big.NewInt(1 << 0)
)

type PostAdminCompactRequest struct {
	// Optional local data-dir replay key scoped by method and path. Receipts are WAL/checkpoint-backed in the local engine. same key plus same raw request body replays the first successful response; same key with a different body returns 409 Conflict.
	IdempotencyKey *string     `json:"-" url:"-"`
	Body           EmptyObject `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostAdminCompactRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAdminCompactRequest) SetIdempotencyKey(idempotencyKey *string) {
	p.IdempotencyKey = idempotencyKey
	p.require(postAdminCompactRequestFieldIdempotencyKey)
}

func (p *PostAdminCompactRequest) UnmarshalJSON(data []byte) error {
	var body EmptyObject
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	p.Body = body
	return nil
}

func (p *PostAdminCompactRequest) MarshalJSON() ([]byte, error) {
	if p.Body == nil {
		return json.Marshal(EmptyObject{})
	}
	return json.Marshal(p.Body)
}

var (
	restoreRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	restoreRequestFieldSource         = big.NewInt(1 << 1)
	restoreRequestFieldTarget         = big.NewInt(1 << 2)
	restoreRequestFieldVerifyRecord   = big.NewInt(1 << 3)
)

type RestoreRequest struct {
	// Optional local data-dir replay key scoped by method and path. Receipts are WAL/checkpoint-backed in the local engine. same key plus same raw request body replays the first successful response; same key with a different body returns 409 Conflict.
	IdempotencyKey *string           `json:"-" url:"-"`
	Source         *string           `json:"source,omitempty" url:"-"`
	Target         *string           `json:"target,omitempty" url:"-"`
	VerifyRecord   *RecordGetRequest `json:"verify_record,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RestoreRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RestoreRequest) SetIdempotencyKey(idempotencyKey *string) {
	r.IdempotencyKey = idempotencyKey
	r.require(restoreRequestFieldIdempotencyKey)
}

// SetSource sets the Source field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RestoreRequest) SetSource(source *string) {
	r.Source = source
	r.require(restoreRequestFieldSource)
}

// SetTarget sets the Target field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RestoreRequest) SetTarget(target *string) {
	r.Target = target
	r.require(restoreRequestFieldTarget)
}

// SetVerifyRecord sets the VerifyRecord field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RestoreRequest) SetVerifyRecord(verifyRecord *RecordGetRequest) {
	r.VerifyRecord = verifyRecord
	r.require(restoreRequestFieldVerifyRecord)
}

func (r *RestoreRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RestoreRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RestoreRequest(body)
	return nil
}

func (r *RestoreRequest) MarshalJSON() ([]byte, error) {
	type embed RestoreRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	snapshotRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	snapshotRequestFieldTarget         = big.NewInt(1 << 1)
)

type SnapshotRequest struct {
	// Optional local data-dir replay key scoped by method and path. Receipts are WAL/checkpoint-backed in the local engine. same key plus same raw request body replays the first successful response; same key with a different body returns 409 Conflict.
	IdempotencyKey *string `json:"-" url:"-"`
	Target         *string `json:"target,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SnapshotRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SnapshotRequest) SetIdempotencyKey(idempotencyKey *string) {
	s.IdempotencyKey = idempotencyKey
	s.require(snapshotRequestFieldIdempotencyKey)
}

// SetTarget sets the Target field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SnapshotRequest) SetTarget(target *string) {
	s.Target = target
	s.require(snapshotRequestFieldTarget)
}

func (s *SnapshotRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SnapshotRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SnapshotRequest(body)
	return nil
}

func (s *SnapshotRequest) MarshalJSON() ([]byte, error) {
	type embed SnapshotRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// Admin job queue entry.
var (
	adminJobFieldQueue = big.NewInt(1 << 0)
	adminJobFieldState = big.NewInt(1 << 1)
)

type AdminJob struct {
	Queue *string `json:"queue,omitempty" url:"queue,omitempty"`
	State *string `json:"state,omitempty" url:"state,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AdminJob) GetQueue() *string {
	if a == nil {
		return nil
	}
	return a.Queue
}

func (a *AdminJob) GetState() *string {
	if a == nil {
		return nil
	}
	return a.State
}

func (a *AdminJob) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AdminJob) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetQueue sets the Queue field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AdminJob) SetQueue(queue *string) {
	a.Queue = queue
	a.require(adminJobFieldQueue)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AdminJob) SetState(state *string) {
	a.State = state
	a.require(adminJobFieldState)
}

func (a *AdminJob) UnmarshalJSON(data []byte) error {
	type unmarshaler AdminJob
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AdminJob(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AdminJob) MarshalJSON() ([]byte, error) {
	type embed AdminJob
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AdminJob) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// Compact response.
var (
	compactResponseFieldCompacted = big.NewInt(1 << 0)
)

type CompactResponse struct {
	Compacted *bool `json:"compacted,omitempty" url:"compacted,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CompactResponse) GetCompacted() *bool {
	if c == nil {
		return nil
	}
	return c.Compacted
}

func (c *CompactResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CompactResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetCompacted sets the Compacted field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CompactResponse) SetCompacted(compacted *bool) {
	c.Compacted = compacted
	c.require(compactResponseFieldCompacted)
}

func (c *CompactResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CompactResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CompactResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CompactResponse) MarshalJSON() ([]byte, error) {
	type embed CompactResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CompactResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Empty JSON object.
type EmptyObject = map[string]any

// Admin job queue response.
var (
	jobsResponseFieldJobs = big.NewInt(1 << 0)
)

type JobsResponse struct {
	Jobs []*AdminJob `json:"jobs,omitempty" url:"jobs,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (j *JobsResponse) GetJobs() []*AdminJob {
	if j == nil {
		return nil
	}
	return j.Jobs
}

func (j *JobsResponse) GetExtraProperties() map[string]interface{} {
	if j == nil {
		return nil
	}
	return j.extraProperties
}

func (j *JobsResponse) require(field *big.Int) {
	if j.explicitFields == nil {
		j.explicitFields = big.NewInt(0)
	}
	j.explicitFields.Or(j.explicitFields, field)
}

// SetJobs sets the Jobs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JobsResponse) SetJobs(jobs []*AdminJob) {
	j.Jobs = jobs
	j.require(jobsResponseFieldJobs)
}

func (j *JobsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler JobsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*j = JobsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *j)
	if err != nil {
		return err
	}
	j.extraProperties = extraProperties
	j.rawJSON = json.RawMessage(data)
	return nil
}

func (j *JobsResponse) MarshalJSON() ([]byte, error) {
	type embed JobsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*j),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, j.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (j *JobsResponse) String() string {
	if j == nil {
		return "<nil>"
	}
	if len(j.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(j.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(j); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", j)
}

// Restore response.
var (
	restoreResponseFieldRestored     = big.NewInt(1 << 0)
	restoreResponseFieldSource       = big.NewInt(1 << 1)
	restoreResponseFieldTarget       = big.NewInt(1 << 2)
	restoreResponseFieldVerification = big.NewInt(1 << 3)
)

type RestoreResponse struct {
	Restored     *bool                `json:"restored,omitempty" url:"restored,omitempty"`
	Source       *string              `json:"source,omitempty" url:"source,omitempty"`
	Target       *string              `json:"target,omitempty" url:"target,omitempty"`
	Verification *RestoreVerification `json:"verification,omitempty" url:"verification,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RestoreResponse) GetRestored() *bool {
	if r == nil {
		return nil
	}
	return r.Restored
}

func (r *RestoreResponse) GetSource() *string {
	if r == nil {
		return nil
	}
	return r.Source
}

func (r *RestoreResponse) GetTarget() *string {
	if r == nil {
		return nil
	}
	return r.Target
}

func (r *RestoreResponse) GetVerification() *RestoreVerification {
	if r == nil {
		return nil
	}
	return r.Verification
}

func (r *RestoreResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RestoreResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetRestored sets the Restored field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RestoreResponse) SetRestored(restored *bool) {
	r.Restored = restored
	r.require(restoreResponseFieldRestored)
}

// SetSource sets the Source field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RestoreResponse) SetSource(source *string) {
	r.Source = source
	r.require(restoreResponseFieldSource)
}

// SetTarget sets the Target field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RestoreResponse) SetTarget(target *string) {
	r.Target = target
	r.require(restoreResponseFieldTarget)
}

// SetVerification sets the Verification field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RestoreResponse) SetVerification(verification *RestoreVerification) {
	r.Verification = verification
	r.require(restoreResponseFieldVerification)
}

func (r *RestoreResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RestoreResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RestoreResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RestoreResponse) MarshalJSON() ([]byte, error) {
	type embed RestoreResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RestoreResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Optional restored-target record verification.
var (
	restoreVerificationFieldRecord        = big.NewInt(1 << 0)
	restoreVerificationFieldRecordVisible = big.NewInt(1 << 1)
	restoreVerificationFieldRequest       = big.NewInt(1 << 2)
	restoreVerificationFieldStatus        = big.NewInt(1 << 3)
)

type RestoreVerification struct {
	Record        *RecordOutput              `json:"record,omitempty" url:"record,omitempty"`
	RecordVisible *bool                      `json:"record_visible,omitempty" url:"record_visible,omitempty"`
	Request       *RecordGetRequest          `json:"request,omitempty" url:"request,omitempty"`
	Status        *RestoreVerificationStatus `json:"status,omitempty" url:"status,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RestoreVerification) GetRecord() *RecordOutput {
	if r == nil {
		return nil
	}
	return r.Record
}

func (r *RestoreVerification) GetRecordVisible() *bool {
	if r == nil {
		return nil
	}
	return r.RecordVisible
}

func (r *RestoreVerification) GetRequest() *RecordGetRequest {
	if r == nil {
		return nil
	}
	return r.Request
}

func (r *RestoreVerification) GetStatus() *RestoreVerificationStatus {
	if r == nil {
		return nil
	}
	return r.Status
}

func (r *RestoreVerification) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RestoreVerification) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetRecord sets the Record field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RestoreVerification) SetRecord(record *RecordOutput) {
	r.Record = record
	r.require(restoreVerificationFieldRecord)
}

// SetRecordVisible sets the RecordVisible field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RestoreVerification) SetRecordVisible(recordVisible *bool) {
	r.RecordVisible = recordVisible
	r.require(restoreVerificationFieldRecordVisible)
}

// SetRequest sets the Request field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RestoreVerification) SetRequest(request *RecordGetRequest) {
	r.Request = request
	r.require(restoreVerificationFieldRequest)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RestoreVerification) SetStatus(status *RestoreVerificationStatus) {
	r.Status = status
	r.require(restoreVerificationFieldStatus)
}

func (r *RestoreVerification) UnmarshalJSON(data []byte) error {
	type unmarshaler RestoreVerification
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RestoreVerification(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RestoreVerification) MarshalJSON() ([]byte, error) {
	type embed RestoreVerification
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RestoreVerification) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type RestoreVerificationStatus string

const (
	RestoreVerificationStatusPassed RestoreVerificationStatus = "passed"
	RestoreVerificationStatusFailed RestoreVerificationStatus = "failed"
)

func NewRestoreVerificationStatusFromString(s string) (RestoreVerificationStatus, error) {
	switch s {
	case "passed":
		return RestoreVerificationStatusPassed, nil
	case "failed":
		return RestoreVerificationStatusFailed, nil
	}
	var t RestoreVerificationStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RestoreVerificationStatus) Ptr() *RestoreVerificationStatus {
	return &r
}

// Snapshot response.
var (
	snapshotResponseFieldSnapshot = big.NewInt(1 << 0)
	snapshotResponseFieldTarget   = big.NewInt(1 << 1)
)

type SnapshotResponse struct {
	Snapshot *bool   `json:"snapshot,omitempty" url:"snapshot,omitempty"`
	Target   *string `json:"target,omitempty" url:"target,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SnapshotResponse) GetSnapshot() *bool {
	if s == nil {
		return nil
	}
	return s.Snapshot
}

func (s *SnapshotResponse) GetTarget() *string {
	if s == nil {
		return nil
	}
	return s.Target
}

func (s *SnapshotResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SnapshotResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetSnapshot sets the Snapshot field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SnapshotResponse) SetSnapshot(snapshot *bool) {
	s.Snapshot = snapshot
	s.require(snapshotResponseFieldSnapshot)
}

// SetTarget sets the Target field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SnapshotResponse) SetTarget(target *string) {
	s.Target = target
	s.require(snapshotResponseFieldTarget)
}

func (s *SnapshotResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SnapshotResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SnapshotResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SnapshotResponse) MarshalJSON() ([]byte, error) {
	type embed SnapshotResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SnapshotResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
