// Code generated by Fern. DO NOT EDIT.

package tracedb

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersGetAdminJobsRequest(t *testing.T) {
	t.Run("SetDatabaseID", func(t *testing.T) {
		obj := &GetAdminJobsRequest{}
		var fernTestValueDatabaseID *string
		obj.SetDatabaseID(fernTestValueDatabaseID)
		assert.Equal(t, fernTestValueDatabaseID, obj.DatabaseID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBranchID", func(t *testing.T) {
		obj := &GetAdminJobsRequest{}
		var fernTestValueBranchID *string
		obj.SetBranchID(fernTestValueBranchID)
		assert.Equal(t, fernTestValueBranchID, obj.BranchID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetAdminJobsRequest(t *testing.T) {
	t.Run("SetDatabaseID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetAdminJobsRequest{}
		var fernTestValueDatabaseID *string

		// Act
		obj.SetDatabaseID(fernTestValueDatabaseID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBranchID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetAdminJobsRequest{}
		var fernTestValueBranchID *string

		// Act
		obj.SetBranchID(fernTestValueBranchID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersPostAdminCompactRequest(t *testing.T) {
	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &PostAdminCompactRequest{}
		var fernTestValueIdempotencyKey *string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitPostAdminCompactRequest(t *testing.T) {
	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PostAdminCompactRequest{}
		var fernTestValueIdempotencyKey *string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersRestoreRequest(t *testing.T) {
	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &RestoreRequest{}
		var fernTestValueIdempotencyKey *string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSource", func(t *testing.T) {
		obj := &RestoreRequest{}
		var fernTestValueSource *string
		obj.SetSource(fernTestValueSource)
		assert.Equal(t, fernTestValueSource, obj.Source)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTarget", func(t *testing.T) {
		obj := &RestoreRequest{}
		var fernTestValueTarget *string
		obj.SetTarget(fernTestValueTarget)
		assert.Equal(t, fernTestValueTarget, obj.Target)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVerifyRecord", func(t *testing.T) {
		obj := &RestoreRequest{}
		var fernTestValueVerifyRecord *RecordGetRequest
		obj.SetVerifyRecord(fernTestValueVerifyRecord)
		assert.Equal(t, fernTestValueVerifyRecord, obj.VerifyRecord)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitRestoreRequest(t *testing.T) {
	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreRequest{}
		var fernTestValueIdempotencyKey *string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSource_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreRequest{}
		var fernTestValueSource *string

		// Act
		obj.SetSource(fernTestValueSource)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTarget_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreRequest{}
		var fernTestValueTarget *string

		// Act
		obj.SetTarget(fernTestValueTarget)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVerifyRecord_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreRequest{}
		var fernTestValueVerifyRecord *RecordGetRequest

		// Act
		obj.SetVerifyRecord(fernTestValueVerifyRecord)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSnapshotRequest(t *testing.T) {
	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &SnapshotRequest{}
		var fernTestValueIdempotencyKey *string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTarget", func(t *testing.T) {
		obj := &SnapshotRequest{}
		var fernTestValueTarget *string
		obj.SetTarget(fernTestValueTarget)
		assert.Equal(t, fernTestValueTarget, obj.Target)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitSnapshotRequest(t *testing.T) {
	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SnapshotRequest{}
		var fernTestValueIdempotencyKey *string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTarget_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SnapshotRequest{}
		var fernTestValueTarget *string

		// Act
		obj.SetTarget(fernTestValueTarget)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersAdminJob(t *testing.T) {
	t.Run("SetQueue", func(t *testing.T) {
		obj := &AdminJob{}
		var fernTestValueQueue *string
		obj.SetQueue(fernTestValueQueue)
		assert.Equal(t, fernTestValueQueue, obj.Queue)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetState", func(t *testing.T) {
		obj := &AdminJob{}
		var fernTestValueState *string
		obj.SetState(fernTestValueState)
		assert.Equal(t, fernTestValueState, obj.State)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersAdminJob(t *testing.T) {
	t.Run("GetQueue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AdminJob{}
		var expected *string
		obj.Queue = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetQueue(), "getter should return the property value")
	})

	t.Run("GetQueue_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AdminJob{}
		obj.Queue = nil

		// Act & Assert
		assert.Nil(t, obj.GetQueue(), "getter should return nil when property is nil")
	})

	t.Run("GetQueue_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AdminJob
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetQueue() // Should return zero value
	})

	t.Run("GetState", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AdminJob{}
		var expected *string
		obj.State = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetState(), "getter should return the property value")
	})

	t.Run("GetState_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AdminJob{}
		obj.State = nil

		// Act & Assert
		assert.Nil(t, obj.GetState(), "getter should return nil when property is nil")
	})

	t.Run("GetState_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AdminJob
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetState() // Should return zero value
	})

}

func TestSettersMarkExplicitAdminJob(t *testing.T) {
	t.Run("SetQueue_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AdminJob{}
		var fernTestValueQueue *string

		// Act
		obj.SetQueue(fernTestValueQueue)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetState_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AdminJob{}
		var fernTestValueState *string

		// Act
		obj.SetState(fernTestValueState)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCompactResponse(t *testing.T) {
	t.Run("SetCompacted", func(t *testing.T) {
		obj := &CompactResponse{}
		var fernTestValueCompacted *bool
		obj.SetCompacted(fernTestValueCompacted)
		assert.Equal(t, fernTestValueCompacted, obj.Compacted)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersCompactResponse(t *testing.T) {
	t.Run("GetCompacted", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CompactResponse{}
		var expected *bool
		obj.Compacted = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCompacted(), "getter should return the property value")
	})

	t.Run("GetCompacted_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CompactResponse{}
		obj.Compacted = nil

		// Act & Assert
		assert.Nil(t, obj.GetCompacted(), "getter should return nil when property is nil")
	})

	t.Run("GetCompacted_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CompactResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCompacted() // Should return zero value
	})

}

func TestSettersMarkExplicitCompactResponse(t *testing.T) {
	t.Run("SetCompacted_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CompactResponse{}
		var fernTestValueCompacted *bool

		// Act
		obj.SetCompacted(fernTestValueCompacted)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersJobsResponse(t *testing.T) {
	t.Run("SetJobs", func(t *testing.T) {
		obj := &JobsResponse{}
		var fernTestValueJobs []*AdminJob
		obj.SetJobs(fernTestValueJobs)
		assert.Equal(t, fernTestValueJobs, obj.Jobs)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersJobsResponse(t *testing.T) {
	t.Run("GetJobs", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &JobsResponse{}
		var expected []*AdminJob
		obj.Jobs = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetJobs(), "getter should return the property value")
	})

	t.Run("GetJobs_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &JobsResponse{}
		obj.Jobs = nil

		// Act & Assert
		assert.Nil(t, obj.GetJobs(), "getter should return nil when property is nil")
	})

	t.Run("GetJobs_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *JobsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetJobs() // Should return zero value
	})

}

func TestSettersMarkExplicitJobsResponse(t *testing.T) {
	t.Run("SetJobs_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &JobsResponse{}
		var fernTestValueJobs []*AdminJob

		// Act
		obj.SetJobs(fernTestValueJobs)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersRestoreResponse(t *testing.T) {
	t.Run("SetRestored", func(t *testing.T) {
		obj := &RestoreResponse{}
		var fernTestValueRestored *bool
		obj.SetRestored(fernTestValueRestored)
		assert.Equal(t, fernTestValueRestored, obj.Restored)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSource", func(t *testing.T) {
		obj := &RestoreResponse{}
		var fernTestValueSource *string
		obj.SetSource(fernTestValueSource)
		assert.Equal(t, fernTestValueSource, obj.Source)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTarget", func(t *testing.T) {
		obj := &RestoreResponse{}
		var fernTestValueTarget *string
		obj.SetTarget(fernTestValueTarget)
		assert.Equal(t, fernTestValueTarget, obj.Target)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVerification", func(t *testing.T) {
		obj := &RestoreResponse{}
		var fernTestValueVerification *RestoreVerification
		obj.SetVerification(fernTestValueVerification)
		assert.Equal(t, fernTestValueVerification, obj.Verification)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersRestoreResponse(t *testing.T) {
	t.Run("GetRestored", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreResponse{}
		var expected *bool
		obj.Restored = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRestored(), "getter should return the property value")
	})

	t.Run("GetRestored_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreResponse{}
		obj.Restored = nil

		// Act & Assert
		assert.Nil(t, obj.GetRestored(), "getter should return nil when property is nil")
	})

	t.Run("GetRestored_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RestoreResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRestored() // Should return zero value
	})

	t.Run("GetSource", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreResponse{}
		var expected *string
		obj.Source = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSource(), "getter should return the property value")
	})

	t.Run("GetSource_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreResponse{}
		obj.Source = nil

		// Act & Assert
		assert.Nil(t, obj.GetSource(), "getter should return nil when property is nil")
	})

	t.Run("GetSource_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RestoreResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSource() // Should return zero value
	})

	t.Run("GetTarget", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreResponse{}
		var expected *string
		obj.Target = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTarget(), "getter should return the property value")
	})

	t.Run("GetTarget_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreResponse{}
		obj.Target = nil

		// Act & Assert
		assert.Nil(t, obj.GetTarget(), "getter should return nil when property is nil")
	})

	t.Run("GetTarget_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RestoreResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTarget() // Should return zero value
	})

	t.Run("GetVerification", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreResponse{}
		var expected *RestoreVerification
		obj.Verification = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetVerification(), "getter should return the property value")
	})

	t.Run("GetVerification_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreResponse{}
		obj.Verification = nil

		// Act & Assert
		assert.Nil(t, obj.GetVerification(), "getter should return nil when property is nil")
	})

	t.Run("GetVerification_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RestoreResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetVerification() // Should return zero value
	})

}

func TestSettersMarkExplicitRestoreResponse(t *testing.T) {
	t.Run("SetRestored_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreResponse{}
		var fernTestValueRestored *bool

		// Act
		obj.SetRestored(fernTestValueRestored)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSource_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreResponse{}
		var fernTestValueSource *string

		// Act
		obj.SetSource(fernTestValueSource)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTarget_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreResponse{}
		var fernTestValueTarget *string

		// Act
		obj.SetTarget(fernTestValueTarget)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVerification_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreResponse{}
		var fernTestValueVerification *RestoreVerification

		// Act
		obj.SetVerification(fernTestValueVerification)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersRestoreVerification(t *testing.T) {
	t.Run("SetRecord", func(t *testing.T) {
		obj := &RestoreVerification{}
		var fernTestValueRecord *RecordOutput
		obj.SetRecord(fernTestValueRecord)
		assert.Equal(t, fernTestValueRecord, obj.Record)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRecordVisible", func(t *testing.T) {
		obj := &RestoreVerification{}
		var fernTestValueRecordVisible *bool
		obj.SetRecordVisible(fernTestValueRecordVisible)
		assert.Equal(t, fernTestValueRecordVisible, obj.RecordVisible)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRequest", func(t *testing.T) {
		obj := &RestoreVerification{}
		var fernTestValueRequest *RecordGetRequest
		obj.SetRequest(fernTestValueRequest)
		assert.Equal(t, fernTestValueRequest, obj.Request)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatus", func(t *testing.T) {
		obj := &RestoreVerification{}
		var fernTestValueStatus *RestoreVerificationStatus
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersRestoreVerification(t *testing.T) {
	t.Run("GetRecord", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreVerification{}
		var expected *RecordOutput
		obj.Record = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRecord(), "getter should return the property value")
	})

	t.Run("GetRecord_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreVerification{}
		obj.Record = nil

		// Act & Assert
		assert.Nil(t, obj.GetRecord(), "getter should return nil when property is nil")
	})

	t.Run("GetRecord_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RestoreVerification
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRecord() // Should return zero value
	})

	t.Run("GetRecordVisible", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreVerification{}
		var expected *bool
		obj.RecordVisible = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRecordVisible(), "getter should return the property value")
	})

	t.Run("GetRecordVisible_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreVerification{}
		obj.RecordVisible = nil

		// Act & Assert
		assert.Nil(t, obj.GetRecordVisible(), "getter should return nil when property is nil")
	})

	t.Run("GetRecordVisible_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RestoreVerification
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRecordVisible() // Should return zero value
	})

	t.Run("GetRequest", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreVerification{}
		var expected *RecordGetRequest
		obj.Request = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRequest(), "getter should return the property value")
	})

	t.Run("GetRequest_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreVerification{}
		obj.Request = nil

		// Act & Assert
		assert.Nil(t, obj.GetRequest(), "getter should return nil when property is nil")
	})

	t.Run("GetRequest_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RestoreVerification
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRequest() // Should return zero value
	})

	t.Run("GetStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreVerification{}
		var expected *RestoreVerificationStatus
		obj.Status = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStatus(), "getter should return the property value")
	})

	t.Run("GetStatus_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreVerification{}
		obj.Status = nil

		// Act & Assert
		assert.Nil(t, obj.GetStatus(), "getter should return nil when property is nil")
	})

	t.Run("GetStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RestoreVerification
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStatus() // Should return zero value
	})

}

func TestSettersMarkExplicitRestoreVerification(t *testing.T) {
	t.Run("SetRecord_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreVerification{}
		var fernTestValueRecord *RecordOutput

		// Act
		obj.SetRecord(fernTestValueRecord)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRecordVisible_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreVerification{}
		var fernTestValueRecordVisible *bool

		// Act
		obj.SetRecordVisible(fernTestValueRecordVisible)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRequest_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreVerification{}
		var fernTestValueRequest *RecordGetRequest

		// Act
		obj.SetRequest(fernTestValueRequest)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreVerification{}
		var fernTestValueStatus *RestoreVerificationStatus

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSnapshotResponse(t *testing.T) {
	t.Run("SetSnapshot", func(t *testing.T) {
		obj := &SnapshotResponse{}
		var fernTestValueSnapshot *bool
		obj.SetSnapshot(fernTestValueSnapshot)
		assert.Equal(t, fernTestValueSnapshot, obj.Snapshot)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTarget", func(t *testing.T) {
		obj := &SnapshotResponse{}
		var fernTestValueTarget *string
		obj.SetTarget(fernTestValueTarget)
		assert.Equal(t, fernTestValueTarget, obj.Target)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersSnapshotResponse(t *testing.T) {
	t.Run("GetSnapshot", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SnapshotResponse{}
		var expected *bool
		obj.Snapshot = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSnapshot(), "getter should return the property value")
	})

	t.Run("GetSnapshot_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SnapshotResponse{}
		obj.Snapshot = nil

		// Act & Assert
		assert.Nil(t, obj.GetSnapshot(), "getter should return nil when property is nil")
	})

	t.Run("GetSnapshot_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SnapshotResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSnapshot() // Should return zero value
	})

	t.Run("GetTarget", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SnapshotResponse{}
		var expected *string
		obj.Target = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTarget(), "getter should return the property value")
	})

	t.Run("GetTarget_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SnapshotResponse{}
		obj.Target = nil

		// Act & Assert
		assert.Nil(t, obj.GetTarget(), "getter should return nil when property is nil")
	})

	t.Run("GetTarget_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SnapshotResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTarget() // Should return zero value
	})

}

func TestSettersMarkExplicitSnapshotResponse(t *testing.T) {
	t.Run("SetSnapshot_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SnapshotResponse{}
		var fernTestValueSnapshot *bool

		// Act
		obj.SetSnapshot(fernTestValueSnapshot)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTarget_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SnapshotResponse{}
		var fernTestValueTarget *string

		// Act
		obj.SetTarget(fernTestValueTarget)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingAdminJob(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AdminJob{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled AdminJob
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj AdminJob
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj AdminJob
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingCompactResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CompactResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled CompactResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj CompactResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj CompactResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingJobsResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &JobsResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled JobsResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj JobsResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj JobsResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingRestoreResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled RestoreResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj RestoreResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj RestoreResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingRestoreVerification(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RestoreVerification{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled RestoreVerification
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj RestoreVerification
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj RestoreVerification
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingSnapshotResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SnapshotResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled SnapshotResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj SnapshotResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj SnapshotResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringAdminJob(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &AdminJob{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AdminJob
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringCompactResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &CompactResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CompactResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringJobsResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &JobsResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *JobsResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringRestoreResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &RestoreResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RestoreResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringRestoreVerification(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &RestoreVerification{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RestoreVerification
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringSnapshotResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &SnapshotResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SnapshotResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumRestoreVerificationStatus(t *testing.T) {
	t.Run("NewFromString_passed", func(t *testing.T) {
		t.Parallel()
		val, err := NewRestoreVerificationStatusFromString("passed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, RestoreVerificationStatus("passed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_failed", func(t *testing.T) {
		t.Parallel()
		val, err := NewRestoreVerificationStatusFromString("failed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, RestoreVerificationStatus("failed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewRestoreVerificationStatusFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewRestoreVerificationStatusFromString("passed")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesAdminJob(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &AdminJob{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AdminJob
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesCompactResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &CompactResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *CompactResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesJobsResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &JobsResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *JobsResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesRestoreResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &RestoreResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RestoreResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesRestoreVerification(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &RestoreVerification{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RestoreVerification
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesSnapshotResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &SnapshotResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SnapshotResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
