// Code generated by Fern. DO NOT EDIT.

package tracedb

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersBranchSummary(t *testing.T) {
	t.Run("SetBranchID", func(t *testing.T) {
		obj := &BranchSummary{}
		var fernTestValueBranchID *string
		obj.SetBranchID(fernTestValueBranchID)
		assert.Equal(t, fernTestValueBranchID, obj.BranchID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDatabaseID", func(t *testing.T) {
		obj := &BranchSummary{}
		var fernTestValueDatabaseID *string
		obj.SetDatabaseID(fernTestValueDatabaseID)
		assert.Equal(t, fernTestValueDatabaseID, obj.DatabaseID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEndpoint", func(t *testing.T) {
		obj := &BranchSummary{}
		var fernTestValueEndpoint *string
		obj.SetEndpoint(fernTestValueEndpoint)
		assert.Equal(t, fernTestValueEndpoint, obj.Endpoint)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLatestEpoch", func(t *testing.T) {
		obj := &BranchSummary{}
		var fernTestValueLatestEpoch *int
		obj.SetLatestEpoch(fernTestValueLatestEpoch)
		assert.Equal(t, fernTestValueLatestEpoch, obj.LatestEpoch)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetParentBranchID", func(t *testing.T) {
		obj := &BranchSummary{}
		var fernTestValueParentBranchID *string
		obj.SetParentBranchID(fernTestValueParentBranchID)
		assert.Equal(t, fernTestValueParentBranchID, obj.ParentBranchID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetState", func(t *testing.T) {
		obj := &BranchSummary{}
		var fernTestValueState *string
		obj.SetState(fernTestValueState)
		assert.Equal(t, fernTestValueState, obj.State)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersBranchSummary(t *testing.T) {
	t.Run("GetBranchID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}
		var expected *string
		obj.BranchID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBranchID(), "getter should return the property value")
	})

	t.Run("GetBranchID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}
		obj.BranchID = nil

		// Act & Assert
		assert.Nil(t, obj.GetBranchID(), "getter should return nil when property is nil")
	})

	t.Run("GetBranchID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BranchSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBranchID() // Should return zero value
	})

	t.Run("GetDatabaseID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}
		var expected *string
		obj.DatabaseID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDatabaseID(), "getter should return the property value")
	})

	t.Run("GetDatabaseID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}
		obj.DatabaseID = nil

		// Act & Assert
		assert.Nil(t, obj.GetDatabaseID(), "getter should return nil when property is nil")
	})

	t.Run("GetDatabaseID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BranchSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDatabaseID() // Should return zero value
	})

	t.Run("GetEndpoint", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}
		var expected *string
		obj.Endpoint = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEndpoint(), "getter should return the property value")
	})

	t.Run("GetEndpoint_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}
		obj.Endpoint = nil

		// Act & Assert
		assert.Nil(t, obj.GetEndpoint(), "getter should return nil when property is nil")
	})

	t.Run("GetEndpoint_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BranchSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEndpoint() // Should return zero value
	})

	t.Run("GetLatestEpoch", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}
		var expected *int
		obj.LatestEpoch = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLatestEpoch(), "getter should return the property value")
	})

	t.Run("GetLatestEpoch_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}
		obj.LatestEpoch = nil

		// Act & Assert
		assert.Nil(t, obj.GetLatestEpoch(), "getter should return nil when property is nil")
	})

	t.Run("GetLatestEpoch_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BranchSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLatestEpoch() // Should return zero value
	})

	t.Run("GetParentBranchID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}
		var expected *string
		obj.ParentBranchID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetParentBranchID(), "getter should return the property value")
	})

	t.Run("GetParentBranchID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}
		obj.ParentBranchID = nil

		// Act & Assert
		assert.Nil(t, obj.GetParentBranchID(), "getter should return nil when property is nil")
	})

	t.Run("GetParentBranchID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BranchSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetParentBranchID() // Should return zero value
	})

	t.Run("GetState", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}
		var expected *string
		obj.State = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetState(), "getter should return the property value")
	})

	t.Run("GetState_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}
		obj.State = nil

		// Act & Assert
		assert.Nil(t, obj.GetState(), "getter should return nil when property is nil")
	})

	t.Run("GetState_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BranchSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetState() // Should return zero value
	})

}

func TestSettersMarkExplicitBranchSummary(t *testing.T) {
	t.Run("SetBranchID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}
		var fernTestValueBranchID *string

		// Act
		obj.SetBranchID(fernTestValueBranchID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDatabaseID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}
		var fernTestValueDatabaseID *string

		// Act
		obj.SetDatabaseID(fernTestValueDatabaseID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEndpoint_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}
		var fernTestValueEndpoint *string

		// Act
		obj.SetEndpoint(fernTestValueEndpoint)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLatestEpoch_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}
		var fernTestValueLatestEpoch *int

		// Act
		obj.SetLatestEpoch(fernTestValueLatestEpoch)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetParentBranchID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}
		var fernTestValueParentBranchID *string

		// Act
		obj.SetParentBranchID(fernTestValueParentBranchID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetState_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}
		var fernTestValueState *string

		// Act
		obj.SetState(fernTestValueState)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersBranchesResponse(t *testing.T) {
	t.Run("SetBranches", func(t *testing.T) {
		obj := &BranchesResponse{}
		var fernTestValueBranches []*BranchSummary
		obj.SetBranches(fernTestValueBranches)
		assert.Equal(t, fernTestValueBranches, obj.Branches)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetGateway", func(t *testing.T) {
		obj := &BranchesResponse{}
		var fernTestValueGateway *bool
		obj.SetGateway(fernTestValueGateway)
		assert.Equal(t, fernTestValueGateway, obj.Gateway)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersBranchesResponse(t *testing.T) {
	t.Run("GetBranches", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchesResponse{}
		var expected []*BranchSummary
		obj.Branches = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBranches(), "getter should return the property value")
	})

	t.Run("GetBranches_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchesResponse{}
		obj.Branches = nil

		// Act & Assert
		assert.Nil(t, obj.GetBranches(), "getter should return nil when property is nil")
	})

	t.Run("GetBranches_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BranchesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBranches() // Should return zero value
	})

	t.Run("GetGateway", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchesResponse{}
		var expected *bool
		obj.Gateway = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetGateway(), "getter should return the property value")
	})

	t.Run("GetGateway_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchesResponse{}
		obj.Gateway = nil

		// Act & Assert
		assert.Nil(t, obj.GetGateway(), "getter should return nil when property is nil")
	})

	t.Run("GetGateway_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BranchesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetGateway() // Should return zero value
	})

}

func TestSettersMarkExplicitBranchesResponse(t *testing.T) {
	t.Run("SetBranches_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchesResponse{}
		var fernTestValueBranches []*BranchSummary

		// Act
		obj.SetBranches(fernTestValueBranches)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetGateway_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchesResponse{}
		var fernTestValueGateway *bool

		// Act
		obj.SetGateway(fernTestValueGateway)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDatabaseSummary(t *testing.T) {
	t.Run("SetDatabaseID", func(t *testing.T) {
		obj := &DatabaseSummary{}
		var fernTestValueDatabaseID *string
		obj.SetDatabaseID(fernTestValueDatabaseID)
		assert.Equal(t, fernTestValueDatabaseID, obj.DatabaseID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEndpoint", func(t *testing.T) {
		obj := &DatabaseSummary{}
		var fernTestValueEndpoint *string
		obj.SetEndpoint(fernTestValueEndpoint)
		assert.Equal(t, fernTestValueEndpoint, obj.Endpoint)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &DatabaseSummary{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOrgID", func(t *testing.T) {
		obj := &DatabaseSummary{}
		var fernTestValueOrgID *string
		obj.SetOrgID(fernTestValueOrgID)
		assert.Equal(t, fernTestValueOrgID, obj.OrgID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProjectID", func(t *testing.T) {
		obj := &DatabaseSummary{}
		var fernTestValueProjectID *string
		obj.SetProjectID(fernTestValueProjectID)
		assert.Equal(t, fernTestValueProjectID, obj.ProjectID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRegion", func(t *testing.T) {
		obj := &DatabaseSummary{}
		var fernTestValueRegion *string
		obj.SetRegion(fernTestValueRegion)
		assert.Equal(t, fernTestValueRegion, obj.Region)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersDatabaseSummary(t *testing.T) {
	t.Run("GetDatabaseID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}
		var expected *string
		obj.DatabaseID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDatabaseID(), "getter should return the property value")
	})

	t.Run("GetDatabaseID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}
		obj.DatabaseID = nil

		// Act & Assert
		assert.Nil(t, obj.GetDatabaseID(), "getter should return nil when property is nil")
	})

	t.Run("GetDatabaseID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabaseSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDatabaseID() // Should return zero value
	})

	t.Run("GetEndpoint", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}
		var expected *string
		obj.Endpoint = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEndpoint(), "getter should return the property value")
	})

	t.Run("GetEndpoint_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}
		obj.Endpoint = nil

		// Act & Assert
		assert.Nil(t, obj.GetEndpoint(), "getter should return nil when property is nil")
	})

	t.Run("GetEndpoint_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabaseSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEndpoint() // Should return zero value
	})

	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}
		var expected *string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}
		obj.Name = nil

		// Act & Assert
		assert.Nil(t, obj.GetName(), "getter should return nil when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabaseSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetOrgID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}
		var expected *string
		obj.OrgID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOrgID(), "getter should return the property value")
	})

	t.Run("GetOrgID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}
		obj.OrgID = nil

		// Act & Assert
		assert.Nil(t, obj.GetOrgID(), "getter should return nil when property is nil")
	})

	t.Run("GetOrgID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabaseSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOrgID() // Should return zero value
	})

	t.Run("GetProjectID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}
		var expected *string
		obj.ProjectID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProjectID(), "getter should return the property value")
	})

	t.Run("GetProjectID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}
		obj.ProjectID = nil

		// Act & Assert
		assert.Nil(t, obj.GetProjectID(), "getter should return nil when property is nil")
	})

	t.Run("GetProjectID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabaseSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProjectID() // Should return zero value
	})

	t.Run("GetRegion", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}
		var expected *string
		obj.Region = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRegion(), "getter should return the property value")
	})

	t.Run("GetRegion_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}
		obj.Region = nil

		// Act & Assert
		assert.Nil(t, obj.GetRegion(), "getter should return nil when property is nil")
	})

	t.Run("GetRegion_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabaseSummary
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRegion() // Should return zero value
	})

}

func TestSettersMarkExplicitDatabaseSummary(t *testing.T) {
	t.Run("SetDatabaseID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}
		var fernTestValueDatabaseID *string

		// Act
		obj.SetDatabaseID(fernTestValueDatabaseID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEndpoint_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}
		var fernTestValueEndpoint *string

		// Act
		obj.SetEndpoint(fernTestValueEndpoint)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOrgID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}
		var fernTestValueOrgID *string

		// Act
		obj.SetOrgID(fernTestValueOrgID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProjectID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}
		var fernTestValueProjectID *string

		// Act
		obj.SetProjectID(fernTestValueProjectID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRegion_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}
		var fernTestValueRegion *string

		// Act
		obj.SetRegion(fernTestValueRegion)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDatabasesResponse(t *testing.T) {
	t.Run("SetDatabases", func(t *testing.T) {
		obj := &DatabasesResponse{}
		var fernTestValueDatabases []*DatabaseSummary
		obj.SetDatabases(fernTestValueDatabases)
		assert.Equal(t, fernTestValueDatabases, obj.Databases)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetGateway", func(t *testing.T) {
		obj := &DatabasesResponse{}
		var fernTestValueGateway *bool
		obj.SetGateway(fernTestValueGateway)
		assert.Equal(t, fernTestValueGateway, obj.Gateway)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMode", func(t *testing.T) {
		obj := &DatabasesResponse{}
		var fernTestValueMode *string
		obj.SetMode(fernTestValueMode)
		assert.Equal(t, fernTestValueMode, obj.Mode)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersDatabasesResponse(t *testing.T) {
	t.Run("GetDatabases", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabasesResponse{}
		var expected []*DatabaseSummary
		obj.Databases = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDatabases(), "getter should return the property value")
	})

	t.Run("GetDatabases_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabasesResponse{}
		obj.Databases = nil

		// Act & Assert
		assert.Nil(t, obj.GetDatabases(), "getter should return nil when property is nil")
	})

	t.Run("GetDatabases_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabasesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDatabases() // Should return zero value
	})

	t.Run("GetGateway", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabasesResponse{}
		var expected *bool
		obj.Gateway = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetGateway(), "getter should return the property value")
	})

	t.Run("GetGateway_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabasesResponse{}
		obj.Gateway = nil

		// Act & Assert
		assert.Nil(t, obj.GetGateway(), "getter should return nil when property is nil")
	})

	t.Run("GetGateway_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabasesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetGateway() // Should return zero value
	})

	t.Run("GetMode", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabasesResponse{}
		var expected *string
		obj.Mode = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMode(), "getter should return the property value")
	})

	t.Run("GetMode_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabasesResponse{}
		obj.Mode = nil

		// Act & Assert
		assert.Nil(t, obj.GetMode(), "getter should return nil when property is nil")
	})

	t.Run("GetMode_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabasesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMode() // Should return zero value
	})

}

func TestSettersMarkExplicitDatabasesResponse(t *testing.T) {
	t.Run("SetDatabases_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabasesResponse{}
		var fernTestValueDatabases []*DatabaseSummary

		// Act
		obj.SetDatabases(fernTestValueDatabases)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetGateway_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabasesResponse{}
		var fernTestValueGateway *bool

		// Act
		obj.SetGateway(fernTestValueGateway)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMode_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabasesResponse{}
		var fernTestValueMode *string

		// Act
		obj.SetMode(fernTestValueMode)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingBranchSummary(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchSummary{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled BranchSummary
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj BranchSummary
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj BranchSummary
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingBranchesResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &BranchesResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled BranchesResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj BranchesResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj BranchesResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingDatabaseSummary(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabaseSummary{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled DatabaseSummary
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj DatabaseSummary
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj DatabaseSummary
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingDatabasesResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DatabasesResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled DatabasesResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj DatabasesResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj DatabasesResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringBranchSummary(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &BranchSummary{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BranchSummary
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringBranchesResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &BranchesResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BranchesResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringDatabaseSummary(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &DatabaseSummary{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabaseSummary
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringDatabasesResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &DatabasesResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabasesResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesBranchSummary(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &BranchSummary{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BranchSummary
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesBranchesResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &BranchesResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *BranchesResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesDatabaseSummary(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &DatabaseSummary{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabaseSummary
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesDatabasesResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &DatabasesResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DatabasesResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
