// Code generated by Fern. DO NOT EDIT.

package tracedb

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/Trace-DB/tracedb-go/internal"
	big "math/big"
)

// Branch catalog entry.
var (
	branchSummaryFieldBranchID       = big.NewInt(1 << 0)
	branchSummaryFieldDatabaseID     = big.NewInt(1 << 1)
	branchSummaryFieldEndpoint       = big.NewInt(1 << 2)
	branchSummaryFieldLatestEpoch    = big.NewInt(1 << 3)
	branchSummaryFieldParentBranchID = big.NewInt(1 << 4)
	branchSummaryFieldState          = big.NewInt(1 << 5)
)

type BranchSummary struct {
	BranchID       *string `json:"branch_id,omitempty" url:"branch_id,omitempty"`
	DatabaseID     *string `json:"database_id,omitempty" url:"database_id,omitempty"`
	Endpoint       *string `json:"endpoint,omitempty" url:"endpoint,omitempty"`
	LatestEpoch    *int    `json:"latest_epoch,omitempty" url:"latest_epoch,omitempty"`
	ParentBranchID *string `json:"parent_branch_id,omitempty" url:"parent_branch_id,omitempty"`
	State          *string `json:"state,omitempty" url:"state,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BranchSummary) GetBranchID() *string {
	if b == nil {
		return nil
	}
	return b.BranchID
}

func (b *BranchSummary) GetDatabaseID() *string {
	if b == nil {
		return nil
	}
	return b.DatabaseID
}

func (b *BranchSummary) GetEndpoint() *string {
	if b == nil {
		return nil
	}
	return b.Endpoint
}

func (b *BranchSummary) GetLatestEpoch() *int {
	if b == nil {
		return nil
	}
	return b.LatestEpoch
}

func (b *BranchSummary) GetParentBranchID() *string {
	if b == nil {
		return nil
	}
	return b.ParentBranchID
}

func (b *BranchSummary) GetState() *string {
	if b == nil {
		return nil
	}
	return b.State
}

func (b *BranchSummary) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BranchSummary) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetBranchID sets the BranchID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BranchSummary) SetBranchID(branchID *string) {
	b.BranchID = branchID
	b.require(branchSummaryFieldBranchID)
}

// SetDatabaseID sets the DatabaseID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BranchSummary) SetDatabaseID(databaseID *string) {
	b.DatabaseID = databaseID
	b.require(branchSummaryFieldDatabaseID)
}

// SetEndpoint sets the Endpoint field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BranchSummary) SetEndpoint(endpoint *string) {
	b.Endpoint = endpoint
	b.require(branchSummaryFieldEndpoint)
}

// SetLatestEpoch sets the LatestEpoch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BranchSummary) SetLatestEpoch(latestEpoch *int) {
	b.LatestEpoch = latestEpoch
	b.require(branchSummaryFieldLatestEpoch)
}

// SetParentBranchID sets the ParentBranchID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BranchSummary) SetParentBranchID(parentBranchID *string) {
	b.ParentBranchID = parentBranchID
	b.require(branchSummaryFieldParentBranchID)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BranchSummary) SetState(state *string) {
	b.State = state
	b.require(branchSummaryFieldState)
}

func (b *BranchSummary) UnmarshalJSON(data []byte) error {
	type unmarshaler BranchSummary
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BranchSummary(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BranchSummary) MarshalJSON() ([]byte, error) {
	type embed BranchSummary
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BranchSummary) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

// Branch catalog response.
var (
	branchesResponseFieldBranches = big.NewInt(1 << 0)
	branchesResponseFieldGateway  = big.NewInt(1 << 1)
)

type BranchesResponse struct {
	Branches []*BranchSummary `json:"branches,omitempty" url:"branches,omitempty"`
	Gateway  *bool            `json:"gateway,omitempty" url:"gateway,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BranchesResponse) GetBranches() []*BranchSummary {
	if b == nil {
		return nil
	}
	return b.Branches
}

func (b *BranchesResponse) GetGateway() *bool {
	if b == nil {
		return nil
	}
	return b.Gateway
}

func (b *BranchesResponse) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BranchesResponse) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetBranches sets the Branches field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BranchesResponse) SetBranches(branches []*BranchSummary) {
	b.Branches = branches
	b.require(branchesResponseFieldBranches)
}

// SetGateway sets the Gateway field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BranchesResponse) SetGateway(gateway *bool) {
	b.Gateway = gateway
	b.require(branchesResponseFieldGateway)
}

func (b *BranchesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler BranchesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BranchesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BranchesResponse) MarshalJSON() ([]byte, error) {
	type embed BranchesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BranchesResponse) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

// Database catalog entry.
var (
	databaseSummaryFieldDatabaseID = big.NewInt(1 << 0)
	databaseSummaryFieldEndpoint   = big.NewInt(1 << 1)
	databaseSummaryFieldName       = big.NewInt(1 << 2)
	databaseSummaryFieldOrgID      = big.NewInt(1 << 3)
	databaseSummaryFieldProjectID  = big.NewInt(1 << 4)
	databaseSummaryFieldRegion     = big.NewInt(1 << 5)
)

type DatabaseSummary struct {
	DatabaseID *string `json:"database_id,omitempty" url:"database_id,omitempty"`
	Endpoint   *string `json:"endpoint,omitempty" url:"endpoint,omitempty"`
	Name       *string `json:"name,omitempty" url:"name,omitempty"`
	OrgID      *string `json:"org_id,omitempty" url:"org_id,omitempty"`
	ProjectID  *string `json:"project_id,omitempty" url:"project_id,omitempty"`
	Region     *string `json:"region,omitempty" url:"region,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DatabaseSummary) GetDatabaseID() *string {
	if d == nil {
		return nil
	}
	return d.DatabaseID
}

func (d *DatabaseSummary) GetEndpoint() *string {
	if d == nil {
		return nil
	}
	return d.Endpoint
}

func (d *DatabaseSummary) GetName() *string {
	if d == nil {
		return nil
	}
	return d.Name
}

func (d *DatabaseSummary) GetOrgID() *string {
	if d == nil {
		return nil
	}
	return d.OrgID
}

func (d *DatabaseSummary) GetProjectID() *string {
	if d == nil {
		return nil
	}
	return d.ProjectID
}

func (d *DatabaseSummary) GetRegion() *string {
	if d == nil {
		return nil
	}
	return d.Region
}

func (d *DatabaseSummary) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DatabaseSummary) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetDatabaseID sets the DatabaseID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DatabaseSummary) SetDatabaseID(databaseID *string) {
	d.DatabaseID = databaseID
	d.require(databaseSummaryFieldDatabaseID)
}

// SetEndpoint sets the Endpoint field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DatabaseSummary) SetEndpoint(endpoint *string) {
	d.Endpoint = endpoint
	d.require(databaseSummaryFieldEndpoint)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DatabaseSummary) SetName(name *string) {
	d.Name = name
	d.require(databaseSummaryFieldName)
}

// SetOrgID sets the OrgID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DatabaseSummary) SetOrgID(orgID *string) {
	d.OrgID = orgID
	d.require(databaseSummaryFieldOrgID)
}

// SetProjectID sets the ProjectID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DatabaseSummary) SetProjectID(projectID *string) {
	d.ProjectID = projectID
	d.require(databaseSummaryFieldProjectID)
}

// SetRegion sets the Region field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DatabaseSummary) SetRegion(region *string) {
	d.Region = region
	d.require(databaseSummaryFieldRegion)
}

func (d *DatabaseSummary) UnmarshalJSON(data []byte) error {
	type unmarshaler DatabaseSummary
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DatabaseSummary(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DatabaseSummary) MarshalJSON() ([]byte, error) {
	type embed DatabaseSummary
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DatabaseSummary) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// Database catalog response.
var (
	databasesResponseFieldDatabases = big.NewInt(1 << 0)
	databasesResponseFieldGateway   = big.NewInt(1 << 1)
	databasesResponseFieldMode      = big.NewInt(1 << 2)
)

type DatabasesResponse struct {
	Databases []*DatabaseSummary `json:"databases,omitempty" url:"databases,omitempty"`
	Gateway   *bool              `json:"gateway,omitempty" url:"gateway,omitempty"`
	Mode      *string            `json:"mode,omitempty" url:"mode,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DatabasesResponse) GetDatabases() []*DatabaseSummary {
	if d == nil {
		return nil
	}
	return d.Databases
}

func (d *DatabasesResponse) GetGateway() *bool {
	if d == nil {
		return nil
	}
	return d.Gateway
}

func (d *DatabasesResponse) GetMode() *string {
	if d == nil {
		return nil
	}
	return d.Mode
}

func (d *DatabasesResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DatabasesResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetDatabases sets the Databases field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DatabasesResponse) SetDatabases(databases []*DatabaseSummary) {
	d.Databases = databases
	d.require(databasesResponseFieldDatabases)
}

// SetGateway sets the Gateway field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DatabasesResponse) SetGateway(gateway *bool) {
	d.Gateway = gateway
	d.require(databasesResponseFieldGateway)
}

// SetMode sets the Mode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DatabasesResponse) SetMode(mode *string) {
	d.Mode = mode
	d.require(databasesResponseFieldMode)
}

func (d *DatabasesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DatabasesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DatabasesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DatabasesResponse) MarshalJSON() ([]byte, error) {
	type embed DatabasesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DatabasesResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}
