// Code generated by Fern. DO NOT EDIT.

package tracedb

import (
	json "encoding/json"

	core "github.com/Trace-DB/tracedb-go/core"
)

// Gateway upstream failure.
type BadGatewayError struct {
	*core.APIError
	Body *ErrorResponse
}

func (b *BadGatewayError) UnmarshalJSON(data []byte) error {
	if b.APIError == nil {
		b.APIError = &core.APIError{}
	}
	var body *ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.StatusCode = 502
	b.Body = body
	return nil
}

func (b *BadGatewayError) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

func (b *BadGatewayError) Unwrap() error {
	return b.APIError
}

// Bad request or validation failure.
type BadRequestError struct {
	*core.APIError
	Body *ErrorResponse
}

func (b *BadRequestError) UnmarshalJSON(data []byte) error {
	if b.APIError == nil {
		b.APIError = &core.APIError{}
	}
	var body *ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.StatusCode = 400
	b.Body = body
	return nil
}

func (b *BadRequestError) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

func (b *BadRequestError) Unwrap() error {
	return b.APIError
}

// Idempotency key was reused with a different request body.
type ConflictError struct {
	*core.APIError
	Body *ErrorResponse
}

func (c *ConflictError) UnmarshalJSON(data []byte) error {
	if c.APIError == nil {
		c.APIError = &core.APIError{}
	}
	var body *ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.StatusCode = 409
	c.Body = body
	return nil
}

func (c *ConflictError) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

func (c *ConflictError) Unwrap() error {
	return c.APIError
}

// Engine or gateway failure.
type InternalServerError struct {
	*core.APIError
	Body *ErrorResponse
}

func (i *InternalServerError) UnmarshalJSON(data []byte) error {
	if i.APIError == nil {
		i.APIError = &core.APIError{}
	}
	var body *ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	i.StatusCode = 500
	i.Body = body
	return nil
}

func (i *InternalServerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.Body)
}

func (i *InternalServerError) Unwrap() error {
	return i.APIError
}

// Route not found.
type NotFoundError struct {
	*core.APIError
	Body *ErrorResponse
}

func (n *NotFoundError) UnmarshalJSON(data []byte) error {
	if n.APIError == nil {
		n.APIError = &core.APIError{}
	}
	var body *ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	n.StatusCode = 404
	n.Body = body
	return nil
}

func (n *NotFoundError) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.Body)
}

func (n *NotFoundError) Unwrap() error {
	return n.APIError
}

// Service unavailable.
type ServiceUnavailableError struct {
	*core.APIError
	Body *ErrorResponse
}

func (s *ServiceUnavailableError) UnmarshalJSON(data []byte) error {
	if s.APIError == nil {
		s.APIError = &core.APIError{}
	}
	var body *ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	s.StatusCode = 503
	s.Body = body
	return nil
}

func (s *ServiceUnavailableError) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.Body)
}

func (s *ServiceUnavailableError) Unwrap() error {
	return s.APIError
}

// Gateway rate limit exceeded.
type TooManyRequestsError struct {
	*core.APIError
	Body *ErrorResponse
}

func (t *TooManyRequestsError) UnmarshalJSON(data []byte) error {
	if t.APIError == nil {
		t.APIError = &core.APIError{}
	}
	var body *ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	t.StatusCode = 429
	t.Body = body
	return nil
}

func (t *TooManyRequestsError) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.Body)
}

func (t *TooManyRequestsError) Unwrap() error {
	return t.APIError
}

// Unauthorized gateway request.
type UnauthorizedError struct {
	*core.APIError
	Body *ErrorResponse
}

func (u *UnauthorizedError) UnmarshalJSON(data []byte) error {
	if u.APIError == nil {
		u.APIError = &core.APIError{}
	}
	var body *ErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 401
	u.Body = body
	return nil
}

func (u *UnauthorizedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnauthorizedError) Unwrap() error {
	return u.APIError
}
