// Code generated by Fern. DO NOT EDIT.

package tracedb

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/Trace-DB/tracedb-go/internal"
	big "math/big"
)

// Public-safe metrics response.
var (
	metricsResponseFieldDurableEpoch      = big.NewInt(1 << 0)
	metricsResponseFieldGateway           = big.NewInt(1 << 1)
	metricsResponseFieldIndexCount        = big.NewInt(1 << 2)
	metricsResponseFieldLatestEpoch       = big.NewInt(1 << 3)
	metricsResponseFieldModuleCount       = big.NewInt(1 << 4)
	metricsResponseFieldRateLimitEnabled  = big.NewInt(1 << 5)
	metricsResponseFieldRateLimitRequests = big.NewInt(1 << 6)
	metricsResponseFieldRecoveryState     = big.NewInt(1 << 7)
	metricsResponseFieldRequests          = big.NewInt(1 << 8)
	metricsResponseFieldSchemaCount       = big.NewInt(1 << 9)
	metricsResponseFieldSegmentCount      = big.NewInt(1 << 10)
	metricsResponseFieldService           = big.NewInt(1 << 11)
)

type MetricsResponse struct {
	DurableEpoch      *int    `json:"durable_epoch,omitempty" url:"durable_epoch,omitempty"`
	Gateway           *bool   `json:"gateway,omitempty" url:"gateway,omitempty"`
	IndexCount        *int    `json:"index_count,omitempty" url:"index_count,omitempty"`
	LatestEpoch       *int    `json:"latest_epoch,omitempty" url:"latest_epoch,omitempty"`
	ModuleCount       *int    `json:"module_count,omitempty" url:"module_count,omitempty"`
	RateLimitEnabled  *bool   `json:"rate_limit_enabled,omitempty" url:"rate_limit_enabled,omitempty"`
	RateLimitRequests *int    `json:"rate_limit_requests,omitempty" url:"rate_limit_requests,omitempty"`
	RecoveryState     *string `json:"recovery_state,omitempty" url:"recovery_state,omitempty"`
	Requests          *int    `json:"requests,omitempty" url:"requests,omitempty"`
	SchemaCount       *int    `json:"schema_count,omitempty" url:"schema_count,omitempty"`
	SegmentCount      *int    `json:"segment_count,omitempty" url:"segment_count,omitempty"`
	Service           *string `json:"service,omitempty" url:"service,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MetricsResponse) GetDurableEpoch() *int {
	if m == nil {
		return nil
	}
	return m.DurableEpoch
}

func (m *MetricsResponse) GetGateway() *bool {
	if m == nil {
		return nil
	}
	return m.Gateway
}

func (m *MetricsResponse) GetIndexCount() *int {
	if m == nil {
		return nil
	}
	return m.IndexCount
}

func (m *MetricsResponse) GetLatestEpoch() *int {
	if m == nil {
		return nil
	}
	return m.LatestEpoch
}

func (m *MetricsResponse) GetModuleCount() *int {
	if m == nil {
		return nil
	}
	return m.ModuleCount
}

func (m *MetricsResponse) GetRateLimitEnabled() *bool {
	if m == nil {
		return nil
	}
	return m.RateLimitEnabled
}

func (m *MetricsResponse) GetRateLimitRequests() *int {
	if m == nil {
		return nil
	}
	return m.RateLimitRequests
}

func (m *MetricsResponse) GetRecoveryState() *string {
	if m == nil {
		return nil
	}
	return m.RecoveryState
}

func (m *MetricsResponse) GetRequests() *int {
	if m == nil {
		return nil
	}
	return m.Requests
}

func (m *MetricsResponse) GetSchemaCount() *int {
	if m == nil {
		return nil
	}
	return m.SchemaCount
}

func (m *MetricsResponse) GetSegmentCount() *int {
	if m == nil {
		return nil
	}
	return m.SegmentCount
}

func (m *MetricsResponse) GetService() *string {
	if m == nil {
		return nil
	}
	return m.Service
}

func (m *MetricsResponse) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MetricsResponse) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetDurableEpoch sets the DurableEpoch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MetricsResponse) SetDurableEpoch(durableEpoch *int) {
	m.DurableEpoch = durableEpoch
	m.require(metricsResponseFieldDurableEpoch)
}

// SetGateway sets the Gateway field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MetricsResponse) SetGateway(gateway *bool) {
	m.Gateway = gateway
	m.require(metricsResponseFieldGateway)
}

// SetIndexCount sets the IndexCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MetricsResponse) SetIndexCount(indexCount *int) {
	m.IndexCount = indexCount
	m.require(metricsResponseFieldIndexCount)
}

// SetLatestEpoch sets the LatestEpoch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MetricsResponse) SetLatestEpoch(latestEpoch *int) {
	m.LatestEpoch = latestEpoch
	m.require(metricsResponseFieldLatestEpoch)
}

// SetModuleCount sets the ModuleCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MetricsResponse) SetModuleCount(moduleCount *int) {
	m.ModuleCount = moduleCount
	m.require(metricsResponseFieldModuleCount)
}

// SetRateLimitEnabled sets the RateLimitEnabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MetricsResponse) SetRateLimitEnabled(rateLimitEnabled *bool) {
	m.RateLimitEnabled = rateLimitEnabled
	m.require(metricsResponseFieldRateLimitEnabled)
}

// SetRateLimitRequests sets the RateLimitRequests field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MetricsResponse) SetRateLimitRequests(rateLimitRequests *int) {
	m.RateLimitRequests = rateLimitRequests
	m.require(metricsResponseFieldRateLimitRequests)
}

// SetRecoveryState sets the RecoveryState field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MetricsResponse) SetRecoveryState(recoveryState *string) {
	m.RecoveryState = recoveryState
	m.require(metricsResponseFieldRecoveryState)
}

// SetRequests sets the Requests field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MetricsResponse) SetRequests(requests *int) {
	m.Requests = requests
	m.require(metricsResponseFieldRequests)
}

// SetSchemaCount sets the SchemaCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MetricsResponse) SetSchemaCount(schemaCount *int) {
	m.SchemaCount = schemaCount
	m.require(metricsResponseFieldSchemaCount)
}

// SetSegmentCount sets the SegmentCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MetricsResponse) SetSegmentCount(segmentCount *int) {
	m.SegmentCount = segmentCount
	m.require(metricsResponseFieldSegmentCount)
}

// SetService sets the Service field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MetricsResponse) SetService(service *string) {
	m.Service = service
	m.require(metricsResponseFieldService)
}

func (m *MetricsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MetricsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MetricsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MetricsResponse) MarshalJSON() ([]byte, error) {
	type embed MetricsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MetricsResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}
