// Code generated by Fern. DO NOT EDIT.

package tracedb

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/Trace-DB/tracedb-go/internal"
	big "math/big"
)

// Readiness response.
var (
	readyResponseFieldCatalogDatabases    = big.NewInt(1 << 0)
	readyResponseFieldDurableEpoch        = big.NewInt(1 << 1)
	readyResponseFieldEngineHealthChecked = big.NewInt(1 << 2)
	readyResponseFieldEngineStatusCode    = big.NewInt(1 << 3)
	readyResponseFieldEngineURL           = big.NewInt(1 << 4)
	readyResponseFieldError               = big.NewInt(1 << 5)
	readyResponseFieldLatestEpoch         = big.NewInt(1 << 6)
	readyResponseFieldMeteredRequests     = big.NewInt(1 << 7)
	readyResponseFieldOk                  = big.NewInt(1 << 8)
	readyResponseFieldReady               = big.NewInt(1 << 9)
	readyResponseFieldRecoveryState       = big.NewInt(1 << 10)
	readyResponseFieldService             = big.NewInt(1 << 11)
)

type ReadyResponse struct {
	CatalogDatabases    *int    `json:"catalog_databases,omitempty" url:"catalog_databases,omitempty"`
	DurableEpoch        *int    `json:"durable_epoch,omitempty" url:"durable_epoch,omitempty"`
	EngineHealthChecked *bool   `json:"engine_health_checked,omitempty" url:"engine_health_checked,omitempty"`
	EngineStatusCode    *int    `json:"engine_status_code,omitempty" url:"engine_status_code,omitempty"`
	EngineURL           *string `json:"engine_url,omitempty" url:"engine_url,omitempty"`
	Error               *string `json:"error,omitempty" url:"error,omitempty"`
	LatestEpoch         *int    `json:"latest_epoch,omitempty" url:"latest_epoch,omitempty"`
	MeteredRequests     *int    `json:"metered_requests,omitempty" url:"metered_requests,omitempty"`
	Ok                  *bool   `json:"ok,omitempty" url:"ok,omitempty"`
	Ready               *bool   `json:"ready,omitempty" url:"ready,omitempty"`
	RecoveryState       *string `json:"recovery_state,omitempty" url:"recovery_state,omitempty"`
	Service             *string `json:"service,omitempty" url:"service,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReadyResponse) GetCatalogDatabases() *int {
	if r == nil {
		return nil
	}
	return r.CatalogDatabases
}

func (r *ReadyResponse) GetDurableEpoch() *int {
	if r == nil {
		return nil
	}
	return r.DurableEpoch
}

func (r *ReadyResponse) GetEngineHealthChecked() *bool {
	if r == nil {
		return nil
	}
	return r.EngineHealthChecked
}

func (r *ReadyResponse) GetEngineStatusCode() *int {
	if r == nil {
		return nil
	}
	return r.EngineStatusCode
}

func (r *ReadyResponse) GetEngineURL() *string {
	if r == nil {
		return nil
	}
	return r.EngineURL
}

func (r *ReadyResponse) GetError() *string {
	if r == nil {
		return nil
	}
	return r.Error
}

func (r *ReadyResponse) GetLatestEpoch() *int {
	if r == nil {
		return nil
	}
	return r.LatestEpoch
}

func (r *ReadyResponse) GetMeteredRequests() *int {
	if r == nil {
		return nil
	}
	return r.MeteredRequests
}

func (r *ReadyResponse) GetOk() *bool {
	if r == nil {
		return nil
	}
	return r.Ok
}

func (r *ReadyResponse) GetReady() *bool {
	if r == nil {
		return nil
	}
	return r.Ready
}

func (r *ReadyResponse) GetRecoveryState() *string {
	if r == nil {
		return nil
	}
	return r.RecoveryState
}

func (r *ReadyResponse) GetService() *string {
	if r == nil {
		return nil
	}
	return r.Service
}

func (r *ReadyResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReadyResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetCatalogDatabases sets the CatalogDatabases field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadyResponse) SetCatalogDatabases(catalogDatabases *int) {
	r.CatalogDatabases = catalogDatabases
	r.require(readyResponseFieldCatalogDatabases)
}

// SetDurableEpoch sets the DurableEpoch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadyResponse) SetDurableEpoch(durableEpoch *int) {
	r.DurableEpoch = durableEpoch
	r.require(readyResponseFieldDurableEpoch)
}

// SetEngineHealthChecked sets the EngineHealthChecked field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadyResponse) SetEngineHealthChecked(engineHealthChecked *bool) {
	r.EngineHealthChecked = engineHealthChecked
	r.require(readyResponseFieldEngineHealthChecked)
}

// SetEngineStatusCode sets the EngineStatusCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadyResponse) SetEngineStatusCode(engineStatusCode *int) {
	r.EngineStatusCode = engineStatusCode
	r.require(readyResponseFieldEngineStatusCode)
}

// SetEngineURL sets the EngineURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadyResponse) SetEngineURL(engineURL *string) {
	r.EngineURL = engineURL
	r.require(readyResponseFieldEngineURL)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadyResponse) SetError(error_ *string) {
	r.Error = error_
	r.require(readyResponseFieldError)
}

// SetLatestEpoch sets the LatestEpoch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadyResponse) SetLatestEpoch(latestEpoch *int) {
	r.LatestEpoch = latestEpoch
	r.require(readyResponseFieldLatestEpoch)
}

// SetMeteredRequests sets the MeteredRequests field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadyResponse) SetMeteredRequests(meteredRequests *int) {
	r.MeteredRequests = meteredRequests
	r.require(readyResponseFieldMeteredRequests)
}

// SetOk sets the Ok field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadyResponse) SetOk(ok *bool) {
	r.Ok = ok
	r.require(readyResponseFieldOk)
}

// SetReady sets the Ready field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadyResponse) SetReady(ready *bool) {
	r.Ready = ready
	r.require(readyResponseFieldReady)
}

// SetRecoveryState sets the RecoveryState field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadyResponse) SetRecoveryState(recoveryState *string) {
	r.RecoveryState = recoveryState
	r.require(readyResponseFieldRecoveryState)
}

// SetService sets the Service field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadyResponse) SetService(service *string) {
	r.Service = service
	r.require(readyResponseFieldService)
}

func (r *ReadyResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ReadyResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReadyResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReadyResponse) MarshalJSON() ([]byte, error) {
	type embed ReadyResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReadyResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}
