// Code generated by Fern. DO NOT EDIT.

package tracedb

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersReadyResponse(t *testing.T) {
	t.Run("SetCatalogDatabases", func(t *testing.T) {
		obj := &ReadyResponse{}
		var fernTestValueCatalogDatabases *int
		obj.SetCatalogDatabases(fernTestValueCatalogDatabases)
		assert.Equal(t, fernTestValueCatalogDatabases, obj.CatalogDatabases)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDurableEpoch", func(t *testing.T) {
		obj := &ReadyResponse{}
		var fernTestValueDurableEpoch *int
		obj.SetDurableEpoch(fernTestValueDurableEpoch)
		assert.Equal(t, fernTestValueDurableEpoch, obj.DurableEpoch)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEngineHealthChecked", func(t *testing.T) {
		obj := &ReadyResponse{}
		var fernTestValueEngineHealthChecked *bool
		obj.SetEngineHealthChecked(fernTestValueEngineHealthChecked)
		assert.Equal(t, fernTestValueEngineHealthChecked, obj.EngineHealthChecked)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEngineStatusCode", func(t *testing.T) {
		obj := &ReadyResponse{}
		var fernTestValueEngineStatusCode *int
		obj.SetEngineStatusCode(fernTestValueEngineStatusCode)
		assert.Equal(t, fernTestValueEngineStatusCode, obj.EngineStatusCode)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEngineURL", func(t *testing.T) {
		obj := &ReadyResponse{}
		var fernTestValueEngineURL *string
		obj.SetEngineURL(fernTestValueEngineURL)
		assert.Equal(t, fernTestValueEngineURL, obj.EngineURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetError", func(t *testing.T) {
		obj := &ReadyResponse{}
		var fernTestValueError *string
		obj.SetError(fernTestValueError)
		assert.Equal(t, fernTestValueError, obj.Error)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLatestEpoch", func(t *testing.T) {
		obj := &ReadyResponse{}
		var fernTestValueLatestEpoch *int
		obj.SetLatestEpoch(fernTestValueLatestEpoch)
		assert.Equal(t, fernTestValueLatestEpoch, obj.LatestEpoch)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMeteredRequests", func(t *testing.T) {
		obj := &ReadyResponse{}
		var fernTestValueMeteredRequests *int
		obj.SetMeteredRequests(fernTestValueMeteredRequests)
		assert.Equal(t, fernTestValueMeteredRequests, obj.MeteredRequests)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOk", func(t *testing.T) {
		obj := &ReadyResponse{}
		var fernTestValueOk *bool
		obj.SetOk(fernTestValueOk)
		assert.Equal(t, fernTestValueOk, obj.Ok)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetReady", func(t *testing.T) {
		obj := &ReadyResponse{}
		var fernTestValueReady *bool
		obj.SetReady(fernTestValueReady)
		assert.Equal(t, fernTestValueReady, obj.Ready)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRecoveryState", func(t *testing.T) {
		obj := &ReadyResponse{}
		var fernTestValueRecoveryState *string
		obj.SetRecoveryState(fernTestValueRecoveryState)
		assert.Equal(t, fernTestValueRecoveryState, obj.RecoveryState)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetService", func(t *testing.T) {
		obj := &ReadyResponse{}
		var fernTestValueService *string
		obj.SetService(fernTestValueService)
		assert.Equal(t, fernTestValueService, obj.Service)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersReadyResponse(t *testing.T) {
	t.Run("GetCatalogDatabases", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var expected *int
		obj.CatalogDatabases = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCatalogDatabases(), "getter should return the property value")
	})

	t.Run("GetCatalogDatabases_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		obj.CatalogDatabases = nil

		// Act & Assert
		assert.Nil(t, obj.GetCatalogDatabases(), "getter should return nil when property is nil")
	})

	t.Run("GetCatalogDatabases_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReadyResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCatalogDatabases() // Should return zero value
	})

	t.Run("GetDurableEpoch", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var expected *int
		obj.DurableEpoch = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDurableEpoch(), "getter should return the property value")
	})

	t.Run("GetDurableEpoch_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		obj.DurableEpoch = nil

		// Act & Assert
		assert.Nil(t, obj.GetDurableEpoch(), "getter should return nil when property is nil")
	})

	t.Run("GetDurableEpoch_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReadyResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDurableEpoch() // Should return zero value
	})

	t.Run("GetEngineHealthChecked", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var expected *bool
		obj.EngineHealthChecked = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEngineHealthChecked(), "getter should return the property value")
	})

	t.Run("GetEngineHealthChecked_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		obj.EngineHealthChecked = nil

		// Act & Assert
		assert.Nil(t, obj.GetEngineHealthChecked(), "getter should return nil when property is nil")
	})

	t.Run("GetEngineHealthChecked_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReadyResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEngineHealthChecked() // Should return zero value
	})

	t.Run("GetEngineStatusCode", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var expected *int
		obj.EngineStatusCode = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEngineStatusCode(), "getter should return the property value")
	})

	t.Run("GetEngineStatusCode_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		obj.EngineStatusCode = nil

		// Act & Assert
		assert.Nil(t, obj.GetEngineStatusCode(), "getter should return nil when property is nil")
	})

	t.Run("GetEngineStatusCode_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReadyResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEngineStatusCode() // Should return zero value
	})

	t.Run("GetEngineURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var expected *string
		obj.EngineURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEngineURL(), "getter should return the property value")
	})

	t.Run("GetEngineURL_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		obj.EngineURL = nil

		// Act & Assert
		assert.Nil(t, obj.GetEngineURL(), "getter should return nil when property is nil")
	})

	t.Run("GetEngineURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReadyResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEngineURL() // Should return zero value
	})

	t.Run("GetError", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var expected *string
		obj.Error = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetError(), "getter should return the property value")
	})

	t.Run("GetError_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		obj.Error = nil

		// Act & Assert
		assert.Nil(t, obj.GetError(), "getter should return nil when property is nil")
	})

	t.Run("GetError_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReadyResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetError() // Should return zero value
	})

	t.Run("GetLatestEpoch", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var expected *int
		obj.LatestEpoch = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLatestEpoch(), "getter should return the property value")
	})

	t.Run("GetLatestEpoch_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		obj.LatestEpoch = nil

		// Act & Assert
		assert.Nil(t, obj.GetLatestEpoch(), "getter should return nil when property is nil")
	})

	t.Run("GetLatestEpoch_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReadyResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLatestEpoch() // Should return zero value
	})

	t.Run("GetMeteredRequests", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var expected *int
		obj.MeteredRequests = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMeteredRequests(), "getter should return the property value")
	})

	t.Run("GetMeteredRequests_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		obj.MeteredRequests = nil

		// Act & Assert
		assert.Nil(t, obj.GetMeteredRequests(), "getter should return nil when property is nil")
	})

	t.Run("GetMeteredRequests_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReadyResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMeteredRequests() // Should return zero value
	})

	t.Run("GetOk", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var expected *bool
		obj.Ok = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOk(), "getter should return the property value")
	})

	t.Run("GetOk_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		obj.Ok = nil

		// Act & Assert
		assert.Nil(t, obj.GetOk(), "getter should return nil when property is nil")
	})

	t.Run("GetOk_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReadyResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOk() // Should return zero value
	})

	t.Run("GetReady", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var expected *bool
		obj.Ready = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetReady(), "getter should return the property value")
	})

	t.Run("GetReady_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		obj.Ready = nil

		// Act & Assert
		assert.Nil(t, obj.GetReady(), "getter should return nil when property is nil")
	})

	t.Run("GetReady_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReadyResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetReady() // Should return zero value
	})

	t.Run("GetRecoveryState", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var expected *string
		obj.RecoveryState = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRecoveryState(), "getter should return the property value")
	})

	t.Run("GetRecoveryState_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		obj.RecoveryState = nil

		// Act & Assert
		assert.Nil(t, obj.GetRecoveryState(), "getter should return nil when property is nil")
	})

	t.Run("GetRecoveryState_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReadyResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRecoveryState() // Should return zero value
	})

	t.Run("GetService", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var expected *string
		obj.Service = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetService(), "getter should return the property value")
	})

	t.Run("GetService_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		obj.Service = nil

		// Act & Assert
		assert.Nil(t, obj.GetService(), "getter should return nil when property is nil")
	})

	t.Run("GetService_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReadyResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetService() // Should return zero value
	})

}

func TestSettersMarkExplicitReadyResponse(t *testing.T) {
	t.Run("SetCatalogDatabases_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var fernTestValueCatalogDatabases *int

		// Act
		obj.SetCatalogDatabases(fernTestValueCatalogDatabases)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDurableEpoch_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var fernTestValueDurableEpoch *int

		// Act
		obj.SetDurableEpoch(fernTestValueDurableEpoch)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEngineHealthChecked_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var fernTestValueEngineHealthChecked *bool

		// Act
		obj.SetEngineHealthChecked(fernTestValueEngineHealthChecked)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEngineStatusCode_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var fernTestValueEngineStatusCode *int

		// Act
		obj.SetEngineStatusCode(fernTestValueEngineStatusCode)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEngineURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var fernTestValueEngineURL *string

		// Act
		obj.SetEngineURL(fernTestValueEngineURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetError_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var fernTestValueError *string

		// Act
		obj.SetError(fernTestValueError)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLatestEpoch_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var fernTestValueLatestEpoch *int

		// Act
		obj.SetLatestEpoch(fernTestValueLatestEpoch)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMeteredRequests_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var fernTestValueMeteredRequests *int

		// Act
		obj.SetMeteredRequests(fernTestValueMeteredRequests)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOk_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var fernTestValueOk *bool

		// Act
		obj.SetOk(fernTestValueOk)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetReady_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var fernTestValueReady *bool

		// Act
		obj.SetReady(fernTestValueReady)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRecoveryState_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var fernTestValueRecoveryState *string

		// Act
		obj.SetRecoveryState(fernTestValueRecoveryState)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetService_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}
		var fernTestValueService *string

		// Act
		obj.SetService(fernTestValueService)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingReadyResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ReadyResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ReadyResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ReadyResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ReadyResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringReadyResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ReadyResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReadyResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesReadyResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ReadyResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ReadyResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
