// Code generated by Fern. DO NOT EDIT.

package tracedb

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersPostInsertRequest(t *testing.T) {
	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &PostInsertRequest{}
		var fernTestValueIdempotencyKey *string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitPostInsertRequest(t *testing.T) {
	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PostInsertRequest{}
		var fernTestValueIdempotencyKey *string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersRecordDeleteRequest(t *testing.T) {
	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &RecordDeleteRequest{}
		var fernTestValueIdempotencyKey *string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetID", func(t *testing.T) {
		obj := &RecordDeleteRequest{}
		var fernTestValueID *string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTable", func(t *testing.T) {
		obj := &RecordDeleteRequest{}
		var fernTestValueTable *string
		obj.SetTable(fernTestValueTable)
		assert.Equal(t, fernTestValueTable, obj.Table)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTenantID", func(t *testing.T) {
		obj := &RecordDeleteRequest{}
		var fernTestValueTenantID *string
		obj.SetTenantID(fernTestValueTenantID)
		assert.Equal(t, fernTestValueTenantID, obj.TenantID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTombstone", func(t *testing.T) {
		obj := &RecordDeleteRequest{}
		var fernTestValueTombstone *string
		obj.SetTombstone(fernTestValueTombstone)
		assert.Equal(t, fernTestValueTombstone, obj.Tombstone)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitRecordDeleteRequest(t *testing.T) {
	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordDeleteRequest{}
		var fernTestValueIdempotencyKey *string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordDeleteRequest{}
		var fernTestValueID *string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTable_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordDeleteRequest{}
		var fernTestValueTable *string

		// Act
		obj.SetTable(fernTestValueTable)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTenantID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordDeleteRequest{}
		var fernTestValueTenantID *string

		// Act
		obj.SetTenantID(fernTestValueTenantID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTombstone_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordDeleteRequest{}
		var fernTestValueTombstone *string

		// Act
		obj.SetTombstone(fernTestValueTombstone)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersRecordPatchRequest(t *testing.T) {
	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &RecordPatchRequest{}
		var fernTestValueIdempotencyKey *string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFields", func(t *testing.T) {
		obj := &RecordPatchRequest{}
		var fernTestValueFields map[string]any
		obj.SetFields(fernTestValueFields)
		assert.Equal(t, fernTestValueFields, obj.Fields)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetID", func(t *testing.T) {
		obj := &RecordPatchRequest{}
		var fernTestValueID *string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTable", func(t *testing.T) {
		obj := &RecordPatchRequest{}
		var fernTestValueTable *string
		obj.SetTable(fernTestValueTable)
		assert.Equal(t, fernTestValueTable, obj.Table)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTenantID", func(t *testing.T) {
		obj := &RecordPatchRequest{}
		var fernTestValueTenantID *string
		obj.SetTenantID(fernTestValueTenantID)
		assert.Equal(t, fernTestValueTenantID, obj.TenantID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitRecordPatchRequest(t *testing.T) {
	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPatchRequest{}
		var fernTestValueIdempotencyKey *string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFields_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPatchRequest{}
		var fernTestValueFields map[string]any

		// Act
		obj.SetFields(fernTestValueFields)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPatchRequest{}
		var fernTestValueID *string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTable_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPatchRequest{}
		var fernTestValueTable *string

		// Act
		obj.SetTable(fernTestValueTable)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTenantID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPatchRequest{}
		var fernTestValueTenantID *string

		// Act
		obj.SetTenantID(fernTestValueTenantID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersPostRecordsPutRequest(t *testing.T) {
	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &PostRecordsPutRequest{}
		var fernTestValueIdempotencyKey *string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitPostRecordsPutRequest(t *testing.T) {
	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PostRecordsPutRequest{}
		var fernTestValueIdempotencyKey *string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersRecordPutBatchRequest(t *testing.T) {
	t.Run("SetIdempotencyKey", func(t *testing.T) {
		obj := &RecordPutBatchRequest{}
		var fernTestValueIdempotencyKey *string
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)
		assert.Equal(t, fernTestValueIdempotencyKey, obj.IdempotencyKey)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIncludeWriteTiming", func(t *testing.T) {
		obj := &RecordPutBatchRequest{}
		var fernTestValueIncludeWriteTiming *bool
		obj.SetIncludeWriteTiming(fernTestValueIncludeWriteTiming)
		assert.Equal(t, fernTestValueIncludeWriteTiming, obj.IncludeWriteTiming)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRecords", func(t *testing.T) {
		obj := &RecordPutBatchRequest{}
		var fernTestValueRecords []*RecordInput
		obj.SetRecords(fernTestValueRecords)
		assert.Equal(t, fernTestValueRecords, obj.Records)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitRecordPutBatchRequest(t *testing.T) {
	t.Run("SetIdempotencyKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPutBatchRequest{}
		var fernTestValueIdempotencyKey *string

		// Act
		obj.SetIdempotencyKey(fernTestValueIdempotencyKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIncludeWriteTiming_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPutBatchRequest{}
		var fernTestValueIncludeWriteTiming *bool

		// Act
		obj.SetIncludeWriteTiming(fernTestValueIncludeWriteTiming)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRecords_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPutBatchRequest{}
		var fernTestValueRecords []*RecordInput

		// Act
		obj.SetRecords(fernTestValueRecords)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersRecordScanRequest(t *testing.T) {
	t.Run("SetCursor", func(t *testing.T) {
		obj := &RecordScanRequest{}
		var fernTestValueCursor *string
		obj.SetCursor(fernTestValueCursor)
		assert.Equal(t, fernTestValueCursor, obj.Cursor)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLimit", func(t *testing.T) {
		obj := &RecordScanRequest{}
		var fernTestValueLimit *int
		obj.SetLimit(fernTestValueLimit)
		assert.Equal(t, fernTestValueLimit, obj.Limit)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTable", func(t *testing.T) {
		obj := &RecordScanRequest{}
		var fernTestValueTable *string
		obj.SetTable(fernTestValueTable)
		assert.Equal(t, fernTestValueTable, obj.Table)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTenantID", func(t *testing.T) {
		obj := &RecordScanRequest{}
		var fernTestValueTenantID *string
		obj.SetTenantID(fernTestValueTenantID)
		assert.Equal(t, fernTestValueTenantID, obj.TenantID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitRecordScanRequest(t *testing.T) {
	t.Run("SetCursor_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordScanRequest{}
		var fernTestValueCursor *string

		// Act
		obj.SetCursor(fernTestValueCursor)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLimit_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordScanRequest{}
		var fernTestValueLimit *int

		// Act
		obj.SetLimit(fernTestValueLimit)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTable_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordScanRequest{}
		var fernTestValueTable *string

		// Act
		obj.SetTable(fernTestValueTable)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTenantID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordScanRequest{}
		var fernTestValueTenantID *string

		// Act
		obj.SetTenantID(fernTestValueTenantID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDeleteResponse(t *testing.T) {
	t.Run("SetDeleted", func(t *testing.T) {
		obj := &DeleteResponse{}
		var fernTestValueDeleted *bool
		obj.SetDeleted(fernTestValueDeleted)
		assert.Equal(t, fernTestValueDeleted, obj.Deleted)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEpoch", func(t *testing.T) {
		obj := &DeleteResponse{}
		var fernTestValueEpoch *int
		obj.SetEpoch(fernTestValueEpoch)
		assert.Equal(t, fernTestValueEpoch, obj.Epoch)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersDeleteResponse(t *testing.T) {
	t.Run("GetDeleted", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteResponse{}
		var expected *bool
		obj.Deleted = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDeleted(), "getter should return the property value")
	})

	t.Run("GetDeleted_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteResponse{}
		obj.Deleted = nil

		// Act & Assert
		assert.Nil(t, obj.GetDeleted(), "getter should return nil when property is nil")
	})

	t.Run("GetDeleted_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeleteResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDeleted() // Should return zero value
	})

	t.Run("GetEpoch", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteResponse{}
		var expected *int
		obj.Epoch = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEpoch(), "getter should return the property value")
	})

	t.Run("GetEpoch_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteResponse{}
		obj.Epoch = nil

		// Act & Assert
		assert.Nil(t, obj.GetEpoch(), "getter should return nil when property is nil")
	})

	t.Run("GetEpoch_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeleteResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEpoch() // Should return zero value
	})

}

func TestSettersMarkExplicitDeleteResponse(t *testing.T) {
	t.Run("SetDeleted_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteResponse{}
		var fernTestValueDeleted *bool

		// Act
		obj.SetDeleted(fernTestValueDeleted)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEpoch_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteResponse{}
		var fernTestValueEpoch *int

		// Act
		obj.SetEpoch(fernTestValueEpoch)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetRecordResponse(t *testing.T) {
	t.Run("SetRecord", func(t *testing.T) {
		obj := &GetRecordResponse{}
		var fernTestValueRecord *RecordOutput
		obj.SetRecord(fernTestValueRecord)
		assert.Equal(t, fernTestValueRecord, obj.Record)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersGetRecordResponse(t *testing.T) {
	t.Run("GetRecord", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetRecordResponse{}
		var expected *RecordOutput
		obj.Record = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRecord(), "getter should return the property value")
	})

	t.Run("GetRecord_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetRecordResponse{}
		obj.Record = nil

		// Act & Assert
		assert.Nil(t, obj.GetRecord(), "getter should return nil when property is nil")
	})

	t.Run("GetRecord_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetRecordResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRecord() // Should return zero value
	})

}

func TestSettersMarkExplicitGetRecordResponse(t *testing.T) {
	t.Run("SetRecord_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetRecordResponse{}
		var fernTestValueRecord *RecordOutput

		// Act
		obj.SetRecord(fernTestValueRecord)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersPutBatchResponse(t *testing.T) {
	t.Run("SetEpoch", func(t *testing.T) {
		obj := &PutBatchResponse{}
		var fernTestValueEpoch *int
		obj.SetEpoch(fernTestValueEpoch)
		assert.Equal(t, fernTestValueEpoch, obj.Epoch)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRecordCount", func(t *testing.T) {
		obj := &PutBatchResponse{}
		var fernTestValueRecordCount *int
		obj.SetRecordCount(fernTestValueRecordCount)
		assert.Equal(t, fernTestValueRecordCount, obj.RecordCount)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWriteTiming", func(t *testing.T) {
		obj := &PutBatchResponse{}
		var fernTestValueWriteTiming map[string]float64
		obj.SetWriteTiming(fernTestValueWriteTiming)
		assert.Equal(t, fernTestValueWriteTiming, obj.WriteTiming)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersPutBatchResponse(t *testing.T) {
	t.Run("GetEpoch", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PutBatchResponse{}
		var expected *int
		obj.Epoch = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEpoch(), "getter should return the property value")
	})

	t.Run("GetEpoch_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PutBatchResponse{}
		obj.Epoch = nil

		// Act & Assert
		assert.Nil(t, obj.GetEpoch(), "getter should return nil when property is nil")
	})

	t.Run("GetEpoch_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PutBatchResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEpoch() // Should return zero value
	})

	t.Run("GetRecordCount", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PutBatchResponse{}
		var expected *int
		obj.RecordCount = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRecordCount(), "getter should return the property value")
	})

	t.Run("GetRecordCount_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PutBatchResponse{}
		obj.RecordCount = nil

		// Act & Assert
		assert.Nil(t, obj.GetRecordCount(), "getter should return nil when property is nil")
	})

	t.Run("GetRecordCount_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PutBatchResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRecordCount() // Should return zero value
	})

	t.Run("GetWriteTiming", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PutBatchResponse{}
		var expected map[string]float64
		obj.WriteTiming = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWriteTiming(), "getter should return the property value")
	})

	t.Run("GetWriteTiming_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PutBatchResponse{}
		obj.WriteTiming = nil

		// Act & Assert
		assert.Nil(t, obj.GetWriteTiming(), "getter should return nil when property is nil")
	})

	t.Run("GetWriteTiming_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PutBatchResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWriteTiming() // Should return zero value
	})

}

func TestSettersMarkExplicitPutBatchResponse(t *testing.T) {
	t.Run("SetEpoch_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PutBatchResponse{}
		var fernTestValueEpoch *int

		// Act
		obj.SetEpoch(fernTestValueEpoch)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRecordCount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PutBatchResponse{}
		var fernTestValueRecordCount *int

		// Act
		obj.SetRecordCount(fernTestValueRecordCount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWriteTiming_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PutBatchResponse{}
		var fernTestValueWriteTiming map[string]float64

		// Act
		obj.SetWriteTiming(fernTestValueWriteTiming)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersRecordInput(t *testing.T) {
	t.Run("SetFields", func(t *testing.T) {
		obj := &RecordInput{}
		var fernTestValueFields map[string]any
		obj.SetFields(fernTestValueFields)
		assert.Equal(t, fernTestValueFields, obj.Fields)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetID", func(t *testing.T) {
		obj := &RecordInput{}
		var fernTestValueID *string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTable", func(t *testing.T) {
		obj := &RecordInput{}
		var fernTestValueTable *string
		obj.SetTable(fernTestValueTable)
		assert.Equal(t, fernTestValueTable, obj.Table)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTenantID", func(t *testing.T) {
		obj := &RecordInput{}
		var fernTestValueTenantID *string
		obj.SetTenantID(fernTestValueTenantID)
		assert.Equal(t, fernTestValueTenantID, obj.TenantID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersRecordInput(t *testing.T) {
	t.Run("GetFields", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordInput{}
		var expected map[string]any
		obj.Fields = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFields(), "getter should return the property value")
	})

	t.Run("GetFields_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordInput{}
		obj.Fields = nil

		// Act & Assert
		assert.Nil(t, obj.GetFields(), "getter should return nil when property is nil")
	})

	t.Run("GetFields_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecordInput
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFields() // Should return zero value
	})

	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordInput{}
		var expected *string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordInput{}
		obj.ID = nil

		// Act & Assert
		assert.Nil(t, obj.GetID(), "getter should return nil when property is nil")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecordInput
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetTable", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordInput{}
		var expected *string
		obj.Table = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTable(), "getter should return the property value")
	})

	t.Run("GetTable_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordInput{}
		obj.Table = nil

		// Act & Assert
		assert.Nil(t, obj.GetTable(), "getter should return nil when property is nil")
	})

	t.Run("GetTable_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecordInput
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTable() // Should return zero value
	})

	t.Run("GetTenantID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordInput{}
		var expected *string
		obj.TenantID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTenantID(), "getter should return the property value")
	})

	t.Run("GetTenantID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordInput{}
		obj.TenantID = nil

		// Act & Assert
		assert.Nil(t, obj.GetTenantID(), "getter should return nil when property is nil")
	})

	t.Run("GetTenantID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecordInput
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTenantID() // Should return zero value
	})

}

func TestSettersMarkExplicitRecordInput(t *testing.T) {
	t.Run("SetFields_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordInput{}
		var fernTestValueFields map[string]any

		// Act
		obj.SetFields(fernTestValueFields)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordInput{}
		var fernTestValueID *string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTable_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordInput{}
		var fernTestValueTable *string

		// Act
		obj.SetTable(fernTestValueTable)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTenantID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordInput{}
		var fernTestValueTenantID *string

		// Act
		obj.SetTenantID(fernTestValueTenantID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestGettersRecordPutBody(t *testing.T) {
	t.Run("GetRecordInput", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPutBody{}
		var expected *RecordInput
		obj.RecordInput = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRecordInput(), "getter should return the property value")
	})

	t.Run("GetRecordInput_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPutBody{}
		obj.RecordInput = nil

		// Act & Assert
		assert.Nil(t, obj.GetRecordInput(), "getter should return nil when property is nil")
	})

	t.Run("GetRecordInput_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecordPutBody
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRecordInput() // Should return zero value
	})

	t.Run("GetRecordPutRequest", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPutBody{}
		var expected *RecordPutRequest
		obj.RecordPutRequest = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRecordPutRequest(), "getter should return the property value")
	})

	t.Run("GetRecordPutRequest_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPutBody{}
		obj.RecordPutRequest = nil

		// Act & Assert
		assert.Nil(t, obj.GetRecordPutRequest(), "getter should return nil when property is nil")
	})

	t.Run("GetRecordPutRequest_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecordPutBody
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRecordPutRequest() // Should return zero value
	})

}

func TestSettersRecordPutRequest(t *testing.T) {
	t.Run("SetBranchID", func(t *testing.T) {
		obj := &RecordPutRequest{}
		var fernTestValueBranchID *string
		obj.SetBranchID(fernTestValueBranchID)
		assert.Equal(t, fernTestValueBranchID, obj.BranchID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDatabaseID", func(t *testing.T) {
		obj := &RecordPutRequest{}
		var fernTestValueDatabaseID *string
		obj.SetDatabaseID(fernTestValueDatabaseID)
		assert.Equal(t, fernTestValueDatabaseID, obj.DatabaseID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRecord", func(t *testing.T) {
		obj := &RecordPutRequest{}
		var fernTestValueRecord *RecordInput
		obj.SetRecord(fernTestValueRecord)
		assert.Equal(t, fernTestValueRecord, obj.Record)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersRecordPutRequest(t *testing.T) {
	t.Run("GetBranchID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPutRequest{}
		var expected *string
		obj.BranchID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBranchID(), "getter should return the property value")
	})

	t.Run("GetBranchID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPutRequest{}
		obj.BranchID = nil

		// Act & Assert
		assert.Nil(t, obj.GetBranchID(), "getter should return nil when property is nil")
	})

	t.Run("GetBranchID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecordPutRequest
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBranchID() // Should return zero value
	})

	t.Run("GetDatabaseID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPutRequest{}
		var expected *string
		obj.DatabaseID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDatabaseID(), "getter should return the property value")
	})

	t.Run("GetDatabaseID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPutRequest{}
		obj.DatabaseID = nil

		// Act & Assert
		assert.Nil(t, obj.GetDatabaseID(), "getter should return nil when property is nil")
	})

	t.Run("GetDatabaseID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecordPutRequest
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDatabaseID() // Should return zero value
	})

	t.Run("GetRecord", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPutRequest{}
		var expected *RecordInput
		obj.Record = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRecord(), "getter should return the property value")
	})

	t.Run("GetRecord_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPutRequest{}
		obj.Record = nil

		// Act & Assert
		assert.Nil(t, obj.GetRecord(), "getter should return nil when property is nil")
	})

	t.Run("GetRecord_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecordPutRequest
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRecord() // Should return zero value
	})

}

func TestSettersMarkExplicitRecordPutRequest(t *testing.T) {
	t.Run("SetBranchID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPutRequest{}
		var fernTestValueBranchID *string

		// Act
		obj.SetBranchID(fernTestValueBranchID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDatabaseID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPutRequest{}
		var fernTestValueDatabaseID *string

		// Act
		obj.SetDatabaseID(fernTestValueDatabaseID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRecord_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPutRequest{}
		var fernTestValueRecord *RecordInput

		// Act
		obj.SetRecord(fernTestValueRecord)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersRecordScanOutput(t *testing.T) {
	t.Run("SetNextCursor", func(t *testing.T) {
		obj := &RecordScanOutput{}
		var fernTestValueNextCursor *string
		obj.SetNextCursor(fernTestValueNextCursor)
		assert.Equal(t, fernTestValueNextCursor, obj.NextCursor)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRecords", func(t *testing.T) {
		obj := &RecordScanOutput{}
		var fernTestValueRecords []*RecordOutput
		obj.SetRecords(fernTestValueRecords)
		assert.Equal(t, fernTestValueRecords, obj.Records)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetReturnedCount", func(t *testing.T) {
		obj := &RecordScanOutput{}
		var fernTestValueReturnedCount *int
		obj.SetReturnedCount(fernTestValueReturnedCount)
		assert.Equal(t, fernTestValueReturnedCount, obj.ReturnedCount)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersRecordScanOutput(t *testing.T) {
	t.Run("GetNextCursor", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordScanOutput{}
		var expected *string
		obj.NextCursor = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNextCursor(), "getter should return the property value")
	})

	t.Run("GetNextCursor_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordScanOutput{}
		obj.NextCursor = nil

		// Act & Assert
		assert.Nil(t, obj.GetNextCursor(), "getter should return nil when property is nil")
	})

	t.Run("GetNextCursor_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecordScanOutput
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNextCursor() // Should return zero value
	})

	t.Run("GetRecords", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordScanOutput{}
		var expected []*RecordOutput
		obj.Records = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRecords(), "getter should return the property value")
	})

	t.Run("GetRecords_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordScanOutput{}
		obj.Records = nil

		// Act & Assert
		assert.Nil(t, obj.GetRecords(), "getter should return nil when property is nil")
	})

	t.Run("GetRecords_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecordScanOutput
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRecords() // Should return zero value
	})

	t.Run("GetReturnedCount", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordScanOutput{}
		var expected *int
		obj.ReturnedCount = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetReturnedCount(), "getter should return the property value")
	})

	t.Run("GetReturnedCount_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordScanOutput{}
		obj.ReturnedCount = nil

		// Act & Assert
		assert.Nil(t, obj.GetReturnedCount(), "getter should return nil when property is nil")
	})

	t.Run("GetReturnedCount_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecordScanOutput
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetReturnedCount() // Should return zero value
	})

}

func TestSettersMarkExplicitRecordScanOutput(t *testing.T) {
	t.Run("SetNextCursor_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordScanOutput{}
		var fernTestValueNextCursor *string

		// Act
		obj.SetNextCursor(fernTestValueNextCursor)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRecords_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordScanOutput{}
		var fernTestValueRecords []*RecordOutput

		// Act
		obj.SetRecords(fernTestValueRecords)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetReturnedCount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordScanOutput{}
		var fernTestValueReturnedCount *int

		// Act
		obj.SetReturnedCount(fernTestValueReturnedCount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingDeleteResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled DeleteResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj DeleteResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj DeleteResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingGetRecordResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetRecordResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled GetRecordResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj GetRecordResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj GetRecordResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingPutBatchResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PutBatchResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled PutBatchResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj PutBatchResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj PutBatchResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingRecordInput(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordInput{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled RecordInput
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj RecordInput
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj RecordInput
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingRecordPutRequest(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordPutRequest{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled RecordPutRequest
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj RecordPutRequest
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj RecordPutRequest
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingRecordScanOutput(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RecordScanOutput{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled RecordScanOutput
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj RecordScanOutput
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj RecordScanOutput
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringDeleteResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &DeleteResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeleteResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringGetRecordResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &GetRecordResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetRecordResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringPutBatchResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &PutBatchResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PutBatchResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringRecordInput(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &RecordInput{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecordInput
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringRecordPutRequest(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &RecordPutRequest{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecordPutRequest
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringRecordScanOutput(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &RecordScanOutput{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecordScanOutput
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesDeleteResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &DeleteResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeleteResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesGetRecordResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &GetRecordResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetRecordResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesPutBatchResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &PutBatchResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PutBatchResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesRecordInput(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &RecordInput{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecordInput
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesRecordPutRequest(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &RecordPutRequest{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecordPutRequest
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesRecordScanOutput(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &RecordScanOutput{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RecordScanOutput
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
