// Code generated by Fern. DO NOT EDIT.

package tracedb

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/Trace-DB/tracedb-go/internal"
	big "math/big"
)

var (
	postInsertRequestFieldIdempotencyKey = big.NewInt(1 << 0)
)

type PostInsertRequest struct {
	// Optional local data-dir replay key scoped by method and path. Receipts are WAL/checkpoint-backed in the local engine. same key plus same raw request body replays the first successful response; same key with a different body returns 409 Conflict.
	IdempotencyKey *string      `json:"-" url:"-"`
	Body           *RecordInput `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostInsertRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostInsertRequest) SetIdempotencyKey(idempotencyKey *string) {
	p.IdempotencyKey = idempotencyKey
	p.require(postInsertRequestFieldIdempotencyKey)
}

func (p *PostInsertRequest) UnmarshalJSON(data []byte) error {
	body := new(RecordInput)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	p.Body = body
	return nil
}

func (p *PostInsertRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(p.Body)
}

var (
	recordDeleteRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	recordDeleteRequestFieldID             = big.NewInt(1 << 1)
	recordDeleteRequestFieldTable          = big.NewInt(1 << 2)
	recordDeleteRequestFieldTenantID       = big.NewInt(1 << 3)
	recordDeleteRequestFieldTombstone      = big.NewInt(1 << 4)
)

type RecordDeleteRequest struct {
	// Optional local data-dir replay key scoped by method and path. Receipts are WAL/checkpoint-backed in the local engine. same key plus same raw request body replays the first successful response; same key with a different body returns 409 Conflict.
	IdempotencyKey *string `json:"-" url:"-"`
	ID             *string `json:"id,omitempty" url:"-"`
	Table          *string `json:"table,omitempty" url:"-"`
	TenantID       *string `json:"tenant_id,omitempty" url:"-"`
	Tombstone      *string `json:"tombstone,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RecordDeleteRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordDeleteRequest) SetIdempotencyKey(idempotencyKey *string) {
	r.IdempotencyKey = idempotencyKey
	r.require(recordDeleteRequestFieldIdempotencyKey)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordDeleteRequest) SetID(id *string) {
	r.ID = id
	r.require(recordDeleteRequestFieldID)
}

// SetTable sets the Table field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordDeleteRequest) SetTable(table *string) {
	r.Table = table
	r.require(recordDeleteRequestFieldTable)
}

// SetTenantID sets the TenantID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordDeleteRequest) SetTenantID(tenantID *string) {
	r.TenantID = tenantID
	r.require(recordDeleteRequestFieldTenantID)
}

// SetTombstone sets the Tombstone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordDeleteRequest) SetTombstone(tombstone *string) {
	r.Tombstone = tombstone
	r.require(recordDeleteRequestFieldTombstone)
}

func (r *RecordDeleteRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RecordDeleteRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RecordDeleteRequest(body)
	return nil
}

func (r *RecordDeleteRequest) MarshalJSON() ([]byte, error) {
	type embed RecordDeleteRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	recordPatchRequestFieldIdempotencyKey = big.NewInt(1 << 0)
	recordPatchRequestFieldFields         = big.NewInt(1 << 1)
	recordPatchRequestFieldID             = big.NewInt(1 << 2)
	recordPatchRequestFieldTable          = big.NewInt(1 << 3)
	recordPatchRequestFieldTenantID       = big.NewInt(1 << 4)
)

type RecordPatchRequest struct {
	// Optional local data-dir replay key scoped by method and path. Receipts are WAL/checkpoint-backed in the local engine. same key plus same raw request body replays the first successful response; same key with a different body returns 409 Conflict.
	IdempotencyKey *string `json:"-" url:"-"`
	// Patch field map.
	Fields   map[string]any `json:"fields,omitempty" url:"-"`
	ID       *string        `json:"id,omitempty" url:"-"`
	Table    *string        `json:"table,omitempty" url:"-"`
	TenantID *string        `json:"tenant_id,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RecordPatchRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordPatchRequest) SetIdempotencyKey(idempotencyKey *string) {
	r.IdempotencyKey = idempotencyKey
	r.require(recordPatchRequestFieldIdempotencyKey)
}

// SetFields sets the Fields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordPatchRequest) SetFields(fields map[string]any) {
	r.Fields = fields
	r.require(recordPatchRequestFieldFields)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordPatchRequest) SetID(id *string) {
	r.ID = id
	r.require(recordPatchRequestFieldID)
}

// SetTable sets the Table field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordPatchRequest) SetTable(table *string) {
	r.Table = table
	r.require(recordPatchRequestFieldTable)
}

// SetTenantID sets the TenantID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordPatchRequest) SetTenantID(tenantID *string) {
	r.TenantID = tenantID
	r.require(recordPatchRequestFieldTenantID)
}

func (r *RecordPatchRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RecordPatchRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RecordPatchRequest(body)
	return nil
}

func (r *RecordPatchRequest) MarshalJSON() ([]byte, error) {
	type embed RecordPatchRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	postRecordsPutRequestFieldIdempotencyKey = big.NewInt(1 << 0)
)

type PostRecordsPutRequest struct {
	// Optional local data-dir replay key scoped by method and path. Receipts are WAL/checkpoint-backed in the local engine. same key plus same raw request body replays the first successful response; same key with a different body returns 409 Conflict.
	IdempotencyKey *string        `json:"-" url:"-"`
	Body           *RecordPutBody `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostRecordsPutRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostRecordsPutRequest) SetIdempotencyKey(idempotencyKey *string) {
	p.IdempotencyKey = idempotencyKey
	p.require(postRecordsPutRequestFieldIdempotencyKey)
}

func (p *PostRecordsPutRequest) UnmarshalJSON(data []byte) error {
	body := new(RecordPutBody)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	p.Body = body
	return nil
}

func (p *PostRecordsPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(p.Body)
}

var (
	recordPutBatchRequestFieldIdempotencyKey     = big.NewInt(1 << 0)
	recordPutBatchRequestFieldIncludeWriteTiming = big.NewInt(1 << 1)
	recordPutBatchRequestFieldRecords            = big.NewInt(1 << 2)
)

type RecordPutBatchRequest struct {
	// Optional local data-dir replay key scoped by method and path. Receipts are WAL/checkpoint-backed in the local engine. same key plus same raw request body replays the first successful response; same key with a different body returns 409 Conflict.
	IdempotencyKey     *string        `json:"-" url:"-"`
	IncludeWriteTiming *bool          `json:"include_write_timing,omitempty" url:"-"`
	Records            []*RecordInput `json:"records,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RecordPutBatchRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetIdempotencyKey sets the IdempotencyKey field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordPutBatchRequest) SetIdempotencyKey(idempotencyKey *string) {
	r.IdempotencyKey = idempotencyKey
	r.require(recordPutBatchRequestFieldIdempotencyKey)
}

// SetIncludeWriteTiming sets the IncludeWriteTiming field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordPutBatchRequest) SetIncludeWriteTiming(includeWriteTiming *bool) {
	r.IncludeWriteTiming = includeWriteTiming
	r.require(recordPutBatchRequestFieldIncludeWriteTiming)
}

// SetRecords sets the Records field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordPutBatchRequest) SetRecords(records []*RecordInput) {
	r.Records = records
	r.require(recordPutBatchRequestFieldRecords)
}

func (r *RecordPutBatchRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RecordPutBatchRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RecordPutBatchRequest(body)
	return nil
}

func (r *RecordPutBatchRequest) MarshalJSON() ([]byte, error) {
	type embed RecordPutBatchRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	recordScanRequestFieldCursor   = big.NewInt(1 << 0)
	recordScanRequestFieldLimit    = big.NewInt(1 << 1)
	recordScanRequestFieldTable    = big.NewInt(1 << 2)
	recordScanRequestFieldTenantID = big.NewInt(1 << 3)
)

type RecordScanRequest struct {
	// Opaque cursor returned by the previous scan page.
	Cursor   *string `json:"cursor,omitempty" url:"-"`
	Limit    *int    `json:"limit,omitempty" url:"-"`
	Table    *string `json:"table,omitempty" url:"-"`
	TenantID *string `json:"tenant_id,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RecordScanRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordScanRequest) SetCursor(cursor *string) {
	r.Cursor = cursor
	r.require(recordScanRequestFieldCursor)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordScanRequest) SetLimit(limit *int) {
	r.Limit = limit
	r.require(recordScanRequestFieldLimit)
}

// SetTable sets the Table field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordScanRequest) SetTable(table *string) {
	r.Table = table
	r.require(recordScanRequestFieldTable)
}

// SetTenantID sets the TenantID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordScanRequest) SetTenantID(tenantID *string) {
	r.TenantID = tenantID
	r.require(recordScanRequestFieldTenantID)
}

func (r *RecordScanRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RecordScanRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RecordScanRequest(body)
	return nil
}

func (r *RecordScanRequest) MarshalJSON() ([]byte, error) {
	type embed RecordScanRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// Delete response.
var (
	deleteResponseFieldDeleted = big.NewInt(1 << 0)
	deleteResponseFieldEpoch   = big.NewInt(1 << 1)
)

type DeleteResponse struct {
	Deleted *bool `json:"deleted,omitempty" url:"deleted,omitempty"`
	Epoch   *int  `json:"epoch,omitempty" url:"epoch,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteResponse) GetDeleted() *bool {
	if d == nil {
		return nil
	}
	return d.Deleted
}

func (d *DeleteResponse) GetEpoch() *int {
	if d == nil {
		return nil
	}
	return d.Epoch
}

func (d *DeleteResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeleteResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetDeleted sets the Deleted field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteResponse) SetDeleted(deleted *bool) {
	d.Deleted = deleted
	d.require(deleteResponseFieldDeleted)
}

// SetEpoch sets the Epoch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteResponse) SetEpoch(epoch *int) {
	d.Epoch = epoch
	d.require(deleteResponseFieldEpoch)
}

func (d *DeleteResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// Get record response.
var (
	getRecordResponseFieldRecord = big.NewInt(1 << 0)
)

type GetRecordResponse struct {
	Record *RecordOutput `json:"record,omitempty" url:"record,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetRecordResponse) GetRecord() *RecordOutput {
	if g == nil {
		return nil
	}
	return g.Record
}

func (g *GetRecordResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetRecordResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetRecord sets the Record field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetRecordResponse) SetRecord(record *RecordOutput) {
	g.Record = record
	g.require(getRecordResponseFieldRecord)
}

func (g *GetRecordResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetRecordResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetRecordResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetRecordResponse) MarshalJSON() ([]byte, error) {
	type embed GetRecordResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetRecordResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Batch write response.
var (
	putBatchResponseFieldEpoch       = big.NewInt(1 << 0)
	putBatchResponseFieldRecordCount = big.NewInt(1 << 1)
	putBatchResponseFieldWriteTiming = big.NewInt(1 << 2)
)

type PutBatchResponse struct {
	Epoch       *int `json:"epoch,omitempty" url:"epoch,omitempty"`
	RecordCount *int `json:"record_count,omitempty" url:"record_count,omitempty"`
	// Optional write timing attribution.
	WriteTiming map[string]float64 `json:"write_timing,omitempty" url:"write_timing,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PutBatchResponse) GetEpoch() *int {
	if p == nil {
		return nil
	}
	return p.Epoch
}

func (p *PutBatchResponse) GetRecordCount() *int {
	if p == nil {
		return nil
	}
	return p.RecordCount
}

func (p *PutBatchResponse) GetWriteTiming() map[string]float64 {
	if p == nil {
		return nil
	}
	return p.WriteTiming
}

func (p *PutBatchResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PutBatchResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetEpoch sets the Epoch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PutBatchResponse) SetEpoch(epoch *int) {
	p.Epoch = epoch
	p.require(putBatchResponseFieldEpoch)
}

// SetRecordCount sets the RecordCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PutBatchResponse) SetRecordCount(recordCount *int) {
	p.RecordCount = recordCount
	p.require(putBatchResponseFieldRecordCount)
}

// SetWriteTiming sets the WriteTiming field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PutBatchResponse) SetWriteTiming(writeTiming map[string]float64) {
	p.WriteTiming = writeTiming
	p.require(putBatchResponseFieldWriteTiming)
}

func (p *PutBatchResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PutBatchResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PutBatchResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PutBatchResponse) MarshalJSON() ([]byte, error) {
	type embed PutBatchResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PutBatchResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// TraceDB record input.
var (
	recordInputFieldFields   = big.NewInt(1 << 0)
	recordInputFieldID       = big.NewInt(1 << 1)
	recordInputFieldTable    = big.NewInt(1 << 2)
	recordInputFieldTenantID = big.NewInt(1 << 3)
)

type RecordInput struct {
	// Record field map.
	Fields   map[string]any `json:"fields,omitempty" url:"fields,omitempty"`
	ID       *string        `json:"id,omitempty" url:"id,omitempty"`
	Table    *string        `json:"table,omitempty" url:"table,omitempty"`
	TenantID *string        `json:"tenant_id,omitempty" url:"tenant_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (r *RecordInput) GetFields() map[string]any {
	if r == nil {
		return nil
	}
	return r.Fields
}

func (r *RecordInput) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *RecordInput) GetTable() *string {
	if r == nil {
		return nil
	}
	return r.Table
}

func (r *RecordInput) GetTenantID() *string {
	if r == nil {
		return nil
	}
	return r.TenantID
}

func (r *RecordInput) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.ExtraProperties
}

func (r *RecordInput) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetFields sets the Fields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordInput) SetFields(fields map[string]any) {
	r.Fields = fields
	r.require(recordInputFieldFields)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordInput) SetID(id *string) {
	r.ID = id
	r.require(recordInputFieldID)
}

// SetTable sets the Table field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordInput) SetTable(table *string) {
	r.Table = table
	r.require(recordInputFieldTable)
}

// SetTenantID sets the TenantID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordInput) SetTenantID(tenantID *string) {
	r.TenantID = tenantID
	r.require(recordInputFieldTenantID)
}

func (r *RecordInput) UnmarshalJSON(data []byte) error {
	type embed RecordInput
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = RecordInput(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.ExtraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RecordInput) MarshalJSON() ([]byte, error) {
	type embed RecordInput
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, r.ExtraProperties)
}

func (r *RecordInput) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Full replacement record write body. The server accepts either RecordInput directly or a wrapper with record.
type RecordPutBody struct {
	RecordInput      *RecordInput
	RecordPutRequest *RecordPutRequest

	typ string
}

func (r *RecordPutBody) GetRecordInput() *RecordInput {
	if r == nil {
		return nil
	}
	return r.RecordInput
}

func (r *RecordPutBody) GetRecordPutRequest() *RecordPutRequest {
	if r == nil {
		return nil
	}
	return r.RecordPutRequest
}

func (r *RecordPutBody) UnmarshalJSON(data []byte) error {
	valueRecordInput := new(RecordInput)
	if err := json.Unmarshal(data, &valueRecordInput); err == nil {
		r.typ = "RecordInput"
		r.RecordInput = valueRecordInput
		return nil
	}
	valueRecordPutRequest := new(RecordPutRequest)
	if err := json.Unmarshal(data, &valueRecordPutRequest); err == nil {
		r.typ = "RecordPutRequest"
		r.RecordPutRequest = valueRecordPutRequest
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, r)
}

func (r RecordPutBody) MarshalJSON() ([]byte, error) {
	if r.typ == "RecordInput" || r.RecordInput != nil {
		return json.Marshal(r.RecordInput)
	}
	if r.typ == "RecordPutRequest" || r.RecordPutRequest != nil {
		return json.Marshal(r.RecordPutRequest)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", r)
}

type RecordPutBodyVisitor interface {
	VisitRecordInput(*RecordInput) error
	VisitRecordPutRequest(*RecordPutRequest) error
}

func (r *RecordPutBody) Accept(visitor RecordPutBodyVisitor) error {
	if r.typ == "RecordInput" || r.RecordInput != nil {
		return visitor.VisitRecordInput(r.RecordInput)
	}
	if r.typ == "RecordPutRequest" || r.RecordPutRequest != nil {
		return visitor.VisitRecordPutRequest(r.RecordPutRequest)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", r)
}

// Full replacement record write. The server also accepts RecordInput directly.
var (
	recordPutRequestFieldRecord = big.NewInt(1 << 0)
)

type RecordPutRequest struct {
	Record *RecordInput `json:"record,omitempty" url:"record,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RecordPutRequest) GetRecord() *RecordInput {
	if r == nil {
		return nil
	}
	return r.Record
}

func (r *RecordPutRequest) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RecordPutRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetRecord sets the Record field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordPutRequest) SetRecord(record *RecordInput) {
	r.Record = record
	r.require(recordPutRequestFieldRecord)
}

func (r *RecordPutRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RecordPutRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RecordPutRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RecordPutRequest) MarshalJSON() ([]byte, error) {
	type embed RecordPutRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RecordPutRequest) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Scan output.
var (
	recordScanOutputFieldNextCursor    = big.NewInt(1 << 0)
	recordScanOutputFieldRecords       = big.NewInt(1 << 1)
	recordScanOutputFieldReturnedCount = big.NewInt(1 << 2)
)

type RecordScanOutput struct {
	NextCursor    *string         `json:"next_cursor,omitempty" url:"next_cursor,omitempty"`
	Records       []*RecordOutput `json:"records,omitempty" url:"records,omitempty"`
	ReturnedCount *int            `json:"returned_count,omitempty" url:"returned_count,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RecordScanOutput) GetNextCursor() *string {
	if r == nil {
		return nil
	}
	return r.NextCursor
}

func (r *RecordScanOutput) GetRecords() []*RecordOutput {
	if r == nil {
		return nil
	}
	return r.Records
}

func (r *RecordScanOutput) GetReturnedCount() *int {
	if r == nil {
		return nil
	}
	return r.ReturnedCount
}

func (r *RecordScanOutput) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RecordScanOutput) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordScanOutput) SetNextCursor(nextCursor *string) {
	r.NextCursor = nextCursor
	r.require(recordScanOutputFieldNextCursor)
}

// SetRecords sets the Records field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordScanOutput) SetRecords(records []*RecordOutput) {
	r.Records = records
	r.require(recordScanOutputFieldRecords)
}

// SetReturnedCount sets the ReturnedCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordScanOutput) SetReturnedCount(returnedCount *int) {
	r.ReturnedCount = returnedCount
	r.require(recordScanOutputFieldReturnedCount)
}

func (r *RecordScanOutput) UnmarshalJSON(data []byte) error {
	type unmarshaler RecordScanOutput
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RecordScanOutput(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RecordScanOutput) MarshalJSON() ([]byte, error) {
	type embed RecordScanOutput
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RecordScanOutput) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}
