// Code generated by Fern. DO NOT EDIT.

package tracedb

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/Trace-DB/tracedb-go/internal"
	big "math/big"
)

// Epoch allocation response.
var (
	epochResponseFieldEpoch = big.NewInt(1 << 0)
)

type EpochResponse struct {
	Epoch *int `json:"epoch,omitempty" url:"epoch,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EpochResponse) GetEpoch() *int {
	if e == nil {
		return nil
	}
	return e.Epoch
}

func (e *EpochResponse) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EpochResponse) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetEpoch sets the Epoch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EpochResponse) SetEpoch(epoch *int) {
	e.Epoch = epoch
	e.require(epochResponseFieldEpoch)
}

func (e *EpochResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler EpochResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EpochResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EpochResponse) MarshalJSON() ([]byte, error) {
	type embed EpochResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EpochResponse) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// Error response.
var (
	errorResponseFieldCode  = big.NewInt(1 << 0)
	errorResponseFieldError = big.NewInt(1 << 1)
)

type ErrorResponse struct {
	// Stable machine-readable error code when available; existing clients can continue to read error.
	Code  *string `json:"code,omitempty" url:"code,omitempty"`
	Error *string `json:"error,omitempty" url:"error,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *ErrorResponse) GetCode() *string {
	if e == nil {
		return nil
	}
	return e.Code
}

func (e *ErrorResponse) GetError() *string {
	if e == nil {
		return nil
	}
	return e.Error
}

func (e *ErrorResponse) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *ErrorResponse) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetCode(code *string) {
	e.Code = code
	e.require(errorResponseFieldCode)
}

// SetError sets the Error field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ErrorResponse) SetError(error_ *string) {
	e.Error = error_
	e.require(errorResponseFieldError)
}

func (e *ErrorResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ErrorResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = ErrorResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *ErrorResponse) MarshalJSON() ([]byte, error) {
	type embed ErrorResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *ErrorResponse) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// Get record request.
var (
	recordGetRequestFieldID       = big.NewInt(1 << 0)
	recordGetRequestFieldTable    = big.NewInt(1 << 1)
	recordGetRequestFieldTenantID = big.NewInt(1 << 2)
)

type RecordGetRequest struct {
	ID       *string `json:"id,omitempty" url:"id,omitempty"`
	Table    *string `json:"table,omitempty" url:"table,omitempty"`
	TenantID *string `json:"tenant_id,omitempty" url:"tenant_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	ExtraProperties map[string]interface{} `json:"-" url:"-"`

	rawJSON json.RawMessage
}

func (r *RecordGetRequest) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *RecordGetRequest) GetTable() *string {
	if r == nil {
		return nil
	}
	return r.Table
}

func (r *RecordGetRequest) GetTenantID() *string {
	if r == nil {
		return nil
	}
	return r.TenantID
}

func (r *RecordGetRequest) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.ExtraProperties
}

func (r *RecordGetRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordGetRequest) SetID(id *string) {
	r.ID = id
	r.require(recordGetRequestFieldID)
}

// SetTable sets the Table field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordGetRequest) SetTable(table *string) {
	r.Table = table
	r.require(recordGetRequestFieldTable)
}

// SetTenantID sets the TenantID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordGetRequest) SetTenantID(tenantID *string) {
	r.TenantID = tenantID
	r.require(recordGetRequestFieldTenantID)
}

func (r *RecordGetRequest) UnmarshalJSON(data []byte) error {
	type embed RecordGetRequest
	var unmarshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = RecordGetRequest(unmarshaler.embed)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.ExtraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RecordGetRequest) MarshalJSON() ([]byte, error) {
	type embed RecordGetRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return internal.MarshalJSONWithExtraProperties(explicitMarshaler, r.ExtraProperties)
}

func (r *RecordGetRequest) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// TraceDB visible record output.
var (
	recordOutputFieldFields    = big.NewInt(1 << 0)
	recordOutputFieldID        = big.NewInt(1 << 1)
	recordOutputFieldTable     = big.NewInt(1 << 2)
	recordOutputFieldTenantID  = big.NewInt(1 << 3)
	recordOutputFieldVersionID = big.NewInt(1 << 4)
)

type RecordOutput struct {
	// Record field map.
	Fields    map[string]any `json:"fields,omitempty" url:"fields,omitempty"`
	ID        *string        `json:"id,omitempty" url:"id,omitempty"`
	Table     *string        `json:"table,omitempty" url:"table,omitempty"`
	TenantID  *string        `json:"tenant_id,omitempty" url:"tenant_id,omitempty"`
	VersionID *int           `json:"version_id,omitempty" url:"version_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RecordOutput) GetFields() map[string]any {
	if r == nil {
		return nil
	}
	return r.Fields
}

func (r *RecordOutput) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *RecordOutput) GetTable() *string {
	if r == nil {
		return nil
	}
	return r.Table
}

func (r *RecordOutput) GetTenantID() *string {
	if r == nil {
		return nil
	}
	return r.TenantID
}

func (r *RecordOutput) GetVersionID() *int {
	if r == nil {
		return nil
	}
	return r.VersionID
}

func (r *RecordOutput) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RecordOutput) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetFields sets the Fields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordOutput) SetFields(fields map[string]any) {
	r.Fields = fields
	r.require(recordOutputFieldFields)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordOutput) SetID(id *string) {
	r.ID = id
	r.require(recordOutputFieldID)
}

// SetTable sets the Table field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordOutput) SetTable(table *string) {
	r.Table = table
	r.require(recordOutputFieldTable)
}

// SetTenantID sets the TenantID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordOutput) SetTenantID(tenantID *string) {
	r.TenantID = tenantID
	r.require(recordOutputFieldTenantID)
}

// SetVersionID sets the VersionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RecordOutput) SetVersionID(versionID *int) {
	r.VersionID = versionID
	r.require(recordOutputFieldVersionID)
}

func (r *RecordOutput) UnmarshalJSON(data []byte) error {
	type unmarshaler RecordOutput
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RecordOutput(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RecordOutput) MarshalJSON() ([]byte, error) {
	type embed RecordOutput
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RecordOutput) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}
