// Code generated by Fern. DO NOT EDIT.

package records

import (
	context "context"

	core "github.com/Trace-DB/tracedb-go/core"
	internal "github.com/Trace-DB/tracedb-go/internal"
	option "github.com/Trace-DB/tracedb-go/option"
	tracedb "github.com/Trace-DB/tracedb-go/tracedb"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Deprecated. Use POST /v1/records/put instead. This route remains for backwards compatibility and will be removed in a future release.
func (c *Client) PostInsert(
	ctx context.Context,
	request *tracedb.PostInsertRequest,
	opts ...option.RequestOption,
) (*tracedb.EpochResponse, error) {
	response, err := c.WithRawResponse.PostInsert(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Current TraceDB v1 product route. This OpenAPI artifact is generated from the checked-in route manifest.
func (c *Client) PostRecordsDelete(
	ctx context.Context,
	request *tracedb.RecordDeleteRequest,
	opts ...option.RequestOption,
) (*tracedb.DeleteResponse, error) {
	response, err := c.WithRawResponse.PostRecordsDelete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Current TraceDB v1 product route. This OpenAPI artifact is generated from the checked-in route manifest.
func (c *Client) PostRecordsGet(
	ctx context.Context,
	request *tracedb.RecordGetRequest,
	opts ...option.RequestOption,
) (*tracedb.GetRecordResponse, error) {
	response, err := c.WithRawResponse.PostRecordsGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Current TraceDB v1 product route. This OpenAPI artifact is generated from the checked-in route manifest.
func (c *Client) PostRecordsPatch(
	ctx context.Context,
	request *tracedb.RecordPatchRequest,
	opts ...option.RequestOption,
) (*tracedb.EpochResponse, error) {
	response, err := c.WithRawResponse.PostRecordsPatch(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Current TraceDB v1 product route. This OpenAPI artifact is generated from the checked-in route manifest.
func (c *Client) PostRecordsPut(
	ctx context.Context,
	request *tracedb.PostRecordsPutRequest,
	opts ...option.RequestOption,
) (*tracedb.EpochResponse, error) {
	response, err := c.WithRawResponse.PostRecordsPut(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Current TraceDB v1 product route. This OpenAPI artifact is generated from the checked-in route manifest.
func (c *Client) PostRecordsPutBatch(
	ctx context.Context,
	request *tracedb.RecordPutBatchRequest,
	opts ...option.RequestOption,
) (*tracedb.PutBatchResponse, error) {
	response, err := c.WithRawResponse.PostRecordsPutBatch(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Current TraceDB v1 product route. This OpenAPI artifact is generated from the checked-in route manifest.
func (c *Client) PostRecordsScan(
	ctx context.Context,
	request *tracedb.RecordScanRequest,
	opts ...option.RequestOption,
) (*tracedb.RecordScanOutput, error) {
	response, err := c.WithRawResponse.PostRecordsScan(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
